/* Standalone visual instrument. Source custody stays unchanged; domain, frames, encoding and presentation are explicit. */
(() => {
'use strict';
const $=id=>document.getElementById(id), W=window.WorkDisposition;
const session=AnalyticSession.create(JSON.parse($('sourceBundle').textContent),{bundleSha:$('sourceRevision').content,rendererVersion:BodyRenderer.version,cameraLimits:BodyRenderer.cameraLimits});
const bundle=session.store.bundle,cases=bundle.cases.filter(c=>c.system==='finite_fifo_queue');
const scenarios=new Map(bundle.scenarios.map(s=>[s.id,s]));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>Number.isInteger(x)?String(x):Number(x).toFixed(3).replace(/0+$/,'').replace(/\.$/,'');
const clone=x=>JSON.parse(JSON.stringify(x)), pretty=x=>JSON.stringify(x,null,2);
const S={version:'state-body-view/2',preset:AnalyticSession.preset,a:{scenarioId:'T4M6/A',worldIndex:0,eventIndex:0,anchor:'decision'},b:{scenarioId:'T4M6/B',worldIndex:0,eventIndex:0,anchor:'decision'},compare:false,mode:'overlay',perspective:'now',clock:'native',span:4,h:.6,valueGain:1.35,layers:{surface:true,contours:true,exact:true},slice:{axis:'u',offset:-1.1},camera:{...BodyRenderer.defaultCamera}};
S.instrument={version:'instrument-views/1',active:'body',companion:'none',timeChannels:['ready','unfinished'],xChannel:'ready',yChannel:'unfinished',yMax:null,timeOffset:0,labelVersion:'display-labels/1',transformVersion:'calibration-cwt/1',calibration:{signal:'chirp',mode:'retrospective',endSample:512,row:24,sample:512}};
S.instrument.workspace={...LinkedWorkspace.defaults};
S.instrument.structure={version:'system-lineage/1',lineageChannel:'ready',lineageSource:'queue',selectedIdentity:null};
S.instrument.calibration.kernelOffset=0;
S.instrument.calibration.landscapeVersion='timescale-landscape/1';
S.instrument.calibration.landscapeCamera={...TimescaleLandscape.defaultCamera};
const instrumentDefaults=clone(S.instrument);
let effective=null,lastConfig=null,lastFocus=null,drawerKind=null,blinkSide='A',checkpointId=null,parentCheckpoint=null;
const scene=new BodyRenderer.Scene($('bodyCanvas'),{onCameraChange:c=>{S.camera=c;render();},onPick:p=>openEvidence(p.key||p.category)});
function selected(key){return session.select(S[key]);}
function step(key,delta){const z=selected(key),i=z.w.records.findIndex(r=>r.event_index===z.r.event_index);S[key].eventIndex=z.w.records[Math.max(0,Math.min(z.w.records.length-1,i+delta))].event_index;render();}
function option(v,label){return '<option value="'+esc(v)+'">'+esc(label)+'</option>';}
function selectors(key){const u=key.toUpperCase(),z=selected(key);$('case'+u).innerHTML=cases.map(c=>option(c.case_id,DisplayLabels.caseLabel(bundle,c.case_id).label)).join('');$('case'+u).value=z.s.case_id;const ss=bundle.scenarios.filter(s=>s.case_id===z.s.case_id);$('action'+u).innerHTML=ss.map(s=>option(s.action_id,DisplayLabels.actionLabel(s).label)).join('');$('action'+u).value=z.s.action_id;$('world'+u).innerHTML=z.s.worlds.map((w,i)=>option(i,DisplayLabels.worldLabel(w).label)).join('');$('world'+u).value=S[key].worldIndex;$('anchor'+u).value=S[key].anchor;$('anchor'+u).querySelector('option[value=first_completed_payload]').disabled=!W.anchorFor(z.s,z.w,z.r.event_index,'first_completed_payload').available;}
function chooseCase(key,id){const ss=bundle.scenarios.filter(s=>s.case_id===id);S[key].scenarioId=ss[0].id;S[key].worldIndex=0;S[key].eventIndex=0;S[key].anchor='decision';render();}
function chooseAction(key,id){const c=selected(key).s.case_id;S[key].scenarioId=c+'/'+id;const z=scenarios.get(S[key].scenarioId);S[key].worldIndex=Math.min(S[key].worldIndex,z.worlds.length-1);S[key].eventIndex=Math.min(S[key].eventIndex,z.worlds[S[key].worldIndex].records.at(-1).event_index);render();}
function timeRow(key){const u=key.toUpperCase(),z=selected(key),index=z.w.records.indexOf(z.r),shift=S.clock==='aligned'&&z.anchor.available?z.anchor.anchor_s:0;return '<div class="time-row"><span class="badge '+(key==='b'?'b':'')+'">'+u+'</span><div><div class="time-label"><span>Now '+fmt(z.r.time_s)+' native s · '+esc(z.r.event_kind.replaceAll('_',' '))+'</span><span>Event '+z.r.event_index+' / '+z.w.records.at(-1).event_index+'</span></div><input type="range" aria-label="Ordered now '+u+'" id="now'+u+'" min="0" max="'+(z.w.records.length-1)+'" step="1" value="'+index+'"><div class="time-info">'+(S.clock==='aligned'?(z.anchor.available?'Aligned '+fmt(z.r.time_s-shift)+' s · anchor '+fmt(shift)+' native s · ':'Alignment unavailable · '):'')+'Configured '+z.r.values.rate+' jobs/tick · original deadline '+z.s.deadline_s+' s'+(z.s.worlds.length>1?' · rate unresolved; this is one separate world':'')+'</div></div><div class="step-controls"><button aria-label="Previous event '+u+'" data-step="'+key+':-1" '+(!index?'disabled':'')+'>‹</button><button aria-label="Next event '+u+'" data-step="'+key+':1" '+(index===z.w.records.length-1?'disabled':'')+'>›</button></div></div>';}
function calibration(){return effective.encoding.calibration;}
function historyConfig(){return effective.rendering.history;}
function viewport(){const b=$('bodyCanvas').getBoundingClientRect();return {width:b.width,height:b.height,pixel_ratio:Math.min(window.devicePixelRatio||1,2)};}
function updateCameraStatus(){const c=scene.getCamera(),clip=scene.getClippingStatus();$('sceneStatus').textContent=c.projection+' · zoom '+fmt(c.zoom)+'×';$('bodyCanvas').dataset.camera=JSON.stringify(c);$('fitNotice').textContent=clip.clipped?'Body or reference plane extends outside the view. Use Fit both bodies.':'Selected geometry fits the current view.';$('fitNotice').classList.toggle('clipped',!!clip.clipped);}

function render(){try{
  const a=selected('a'),b=S.compare?selected('b'):null;S.instrument=S.instrument||clone(instrumentDefaults);ensureExtensions();effective=session.compile(S,{viewport:viewport()});$('error').style.display='none';
  selectors('a');selectors('b');$('selectionB').hidden=!S.compare;$('selectionA').classList.toggle('solo',!S.compare);$('compareToggle').textContent=S.compare?'− Remove comparison':'＋ Add comparison';$('comparisonModes').hidden=!S.compare;$('anchorBLabel').hidden=!S.compare;$('timeB').hidden=!S.compare;
  $('nowMode').setAttribute('aria-pressed',S.perspective==='now');$('historyMode').setAttribute('aria-pressed',S.perspective==='history');document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===S.mode));
  $('viewTitle').textContent=S.compare?(S.mode==='soloA'||S.mode==='soloB'||S.mode==='side'?'Equal surface style · shared scale':'A · surface   /   B · amber wireframe'):'A · translucent surface';$('historySpan').value=S.span;$('spanValue').textContent=fmt(S.span)+' s';$('softness').value=S.h;$('softnessValue').textContent=fmt(S.h);$('valueGain').value=S.valueGain;$('gainValue').textContent=fmt(S.valueGain)+'×';$('clockMode').value=S.clock;$('projection').value=S.camera.projection;for(const [id,k]of [['surfaceToggle','surface'],['contourToggle','contours'],['exactToggle','exact']])$(id).checked=S.layers[k];$('sliceAxis').value=S.slice.axis;$('sliceOffset').value=S.slice.offset;$('sliceValue').textContent=fmt(S.slice.offset);
  const anchorText=(z,k)=>k+': '+(z.anchor.available?fmt(z.anchor.anchor_s)+' native s':'unavailable at now');$('anchorNote').textContent=anchorText(a,'A')+(b?' · '+anchorText(b,'B'):'')+'. Shifts affect time coordinates only.';
  if(b&&a.anchor.available&&b.anchor.available){const nativeDelta=b.r.time_s-a.r.time_s,alignedDelta=nativeDelta-(b.anchor.anchor_s-a.anchor.anchor_s);$('anchorNote').textContent+=' B−A now: '+fmt(nativeDelta)+' s native; '+fmt(alignedDelta)+' s with selected anchors.';}
  const alignmentBlocked=S.clock==='aligned'&&(!a.anchor.available||b&&!b.anchor.available);
  lastConfig=session.renderConfig(effective);
  for(const id of ['surfaceToggle','contourToggle','exactToggle'])$(id).disabled=S.perspective==='history';
  scene.render(lastConfig);S.camera=scene.getCamera();updateCameraStatus();$('bodyCanvas').style.visibility=alignmentBlocked&&S.perspective==='history'?'hidden':'visible';$('canvasNote').hidden=S.compare&&S.mode==='side';
  $('canvasNote').innerHTML='<strong>A · Initial case: '+esc(DisplayLabels.caseLabel(bundle,a.s.case_id).label)+' / '+fmt(a.r.time_s)+' s / '+esc(a.r.event_kind.replaceAll('_',' '))+'</strong>'+(b?'<br><strong style="color:#a26727">B · Initial case: '+esc(DisplayLabels.caseLabel(bundle,b.s.case_id).label)+' / '+fmt(b.r.time_s)+' s / '+esc(b.r.event_kind.replaceAll('_',' '))+'</strong>':'')+'<br>'+(S.perspective==='now'?'One selected state per world · no temporal blending':'Category lanes × time × native required-job count');
  $('coordinateLegend').textContent=S.perspective==='now'?'Plane: categorical display positions · height: jobs / display area':'History: category lane × '+S.clock+' seconds × required-job count';$('scaleCaption').textContent='Shared gain '+fmt(S.valueGain)+'× · h '+fmt(S.h)+' · crop ±3.6';
  $('exactStrip').innerHTML=W.categories.map(k=>'<button class="exact-cell" data-category="'+k.key+'" aria-label="Inspect '+k.label+' identities"><span class="name">'+k.label+'</span><span class="number">A '+a.p.weights[k.key]+'</span>'+(b?'<span class="bvalue">B '+b.p.weights[k.key]+'</span>':'')+'<span class="identities">required identities · inspect</span></button>').join('');$('exactStrip').querySelectorAll('button').forEach(el=>el.onclick=()=>openEvidence(el.dataset.category));
  if(S.perspective==='history')$('scaleCaption').textContent='Shared count gain '+fmt(.42*S.valueGain/1.35)+' · state held between events';
  if(b&&W.categories.every(k=>a.p.weights[k.key]===b.p.weights[k.key]))$('canvasNote').innerHTML+='<br><span>Same four counts; identities and action provenance can differ.</span>';
  for(const key of ['a','b']){$('time'+key.toUpperCase()).innerHTML=timeRow(key);$('now'+key.toUpperCase()).oninput=e=>{const z=selected(key);S[key].eventIndex=z.w.records[+e.target.value].event_index;render();};}document.querySelectorAll('[data-step]').forEach(el=>el.onclick=()=>{const[k,d]=el.dataset.step.split(':');step(k,+d);});
  if(alignmentBlocked){$('historySvg').innerHTML='<text x="15" y="55" font-size="12" fill="#903a32">Aligned history withheld: anchor unavailable in this prefix.</text>';$('error').textContent='Alignment unavailable at selected now. Choose a supported anchor. Current now bodies and native values remain valid; aligned history is withheld.';$('error').style.display='block';}else drawHistory(a,b);
  drawProfile(a,b);const mass=W.cropMass(a.p.weights,S.h);$('footerStatus').textContent='Synthetic event states · A '+a.p.total+' required identities · finite crop contains ≈'+fmt(mass)+' count mass; omitted tails retained by the declared kernel.';
  $('bodyCanvas').setAttribute('aria-label','3D '+S.perspective+' body. A '+a.s.id+', '+a.r.event_kind+', '+a.r.time_s+' seconds. '+W.categories.map(k=>k.label+' '+a.p.weights[k.key]).join(', ')+(b?'. Comparison B '+b.s.id+', '+b.r.time_s+' seconds.':'')+' Drag to orbit, shift-drag to pan, wheel to zoom.');
renderInstruments(a,b);
}catch(e){$('error').textContent=e.message;$('error').style.display='block';}}

function renderInstruments(a,b){
 const I=S.instrument,D=DirectInstruments,all=[D.series(a,'a',{...I,clock:S.clock,span:S.span}),...(b?[D.series(b,'b',{...I,clock:S.clock,span:S.span})]:[])];
 document.body.classList.toggle('numeric-active',I.active!=='body');document.body.classList.toggle('timescale-active',I.active==='timescale');document.body.classList.toggle('structure-active',['system','lineage'].includes(I.active));
 document.querySelectorAll('[data-view]').forEach(el=>el.setAttribute('aria-pressed',el.dataset.view===I.active));
 $('companionView').value=I.companion;$('companionView').disabled=I.active==='timescale';$('evidenceButton').textContent=I.active==='timescale'?'Queue evidence / native values':'Evidence / native values';if(I.active==='timescale')$('footerStatus').textContent='Separate synthetic calibration · sampled numeric signal · coefficient magnitude over time and frequency. Queue source remains selected separately above.';$('numericPanel').hidden=!['time','relationship'].includes(I.active);$('timescalePanel').hidden=I.active!=='timescale';$('structurePanel').hidden=!['system','lineage'].includes(I.active);
 $('numericControls').hidden=I.active==='timescale'||!([I.active,I.companion].some(v=>['time','relationship'].includes(v)));
 $('xChannel').value=I.xChannel;$('yChannel').value=I.yChannel;$('numericMax').value=I.yMax??'';$('timePan').value=I.timeOffset;
 document.querySelectorAll('[data-channel]').forEach(el=>el.checked=I.timeChannels.includes(el.dataset.channel));
 $('caseContext').innerHTML=[['a',a],...(b?[['b',b]]:[])].map(([key,z])=>{const label=DisplayLabels.caseLabel(bundle,z.s.case_id),c=cases.find(c=>c.case_id===z.s.case_id),facts=c.facts,rate=facts.service_rate_possibilities_jobs_per_tick;return '<article class="case-description"><h2>'+key.toUpperCase()+' · '+esc(label.label)+'</h2><p>Initially '+facts.pending_fifo_payload_ids.length+' ready jobs; '+c.task.required_payload_ids.length+' required; '+facts.backup_payload_ids.length+' listed backups. Original deadline '+z.s.deadline_s+' s.</p><p><strong>Selected action:</strong> '+esc(DisplayLabels.actionLabel(z.s).label)+'<br><strong>Assumed condition:</strong> '+esc(DisplayLabels.worldLabel(z.w).label)+(rate.length>1?' · actual initial rate unresolved; alternatives stay separate.':' · fixed stipulated model.')+'</p><details><summary>Technical details · '+esc(z.s.id)+'</summary><p>Authored synthetic queue case · source '+esc(bundle.source.sha256)+'<br>Display labels '+esc(DisplayLabels.version)+'</p>'+refs(label.source_refs)+'</details></article>';}).join('');
 $('caseContext').querySelectorAll('[data-pointer]').forEach(el=>el.onclick=()=>openSourceNode(el.dataset.pointer));
 const select=(key,index)=>{S[key].eventIndex=index;render();};
 const caption='Source-derived event values; A solid, B dashed. Shared automatic ranges use the selected prefixes; panning does not rescale them. Each world keeps its own ordered prefix and time window. '+(S.clock==='aligned'?'Event-relative seconds = native seconds − selected anchor. ':'Native seconds. ')+'No samples are taken from the Gaussian body.';
 $('companionPanel').hidden=I.companion==='none'||I.active==='timescale';applyWorkspace();
 const draw=(type,svg,rateSvg)=>drawNumericPlot(type,svg,rateSvg,all,select);
 const title=type=>type==='time'?'Over time':'X–Y Relationship';
 const note=type=>type==='time'?'Steps hold state between stipulated events. Dots are exact records. Offset handles below the axis preserve same-time order; shaded intervals mark an action pause. Rates use a separate lane.':'Points pair two quantities from the same event. Arrows show ordered transitions, not continuous occupancy or physical forces. Labels identify events; point tooltips retain native time and dwell seconds. A line may reflect an accounting identity; a loop alone would not establish oscillation.';
 if(['time','relationship'].includes(I.active)){$('numericTitle').textContent=title(I.active);$('numericCaption').textContent=caption+' '+note(I.active);const out=draw(I.active,$('numericSvg'),$('rateSvg'));$('numericStatus').textContent=(out.clipped?'Some values exceed the selected vertical range. ':'')+(all.every(x=>!x.rows.length)?'No retained state in this window; blank regions do not mean zero. ':'')+(all.some(x=>x.nativeEnd<x.z.r.time_s)?'Selected cursor lies after the panned window; evidence still refers to that selected event. ':'')+all.filter(x=>x.available).map(x=>x.key.toUpperCase()+': window ['+fmt(x.nativeStart)+', '+fmt(x.nativeEnd)+'] native s; ['+fmt(x.start)+', '+fmt(x.end)+'] display s. Original deadline '+x.z.s.deadline_s+' native s ('+fmt(x.deadline)+' display s). Pause '+(x.z.s.action.parameters.pause_ticks||0)+' ticks.').join(' ');}
 $('companionPanel').hidden=I.companion==='none'||I.active==='timescale';
 if(!$('companionPanel').hidden){const structural=['system','lineage'].includes(I.companion);$('companionNumeric').hidden=structural;$('companionStructure').hidden=!structural;if(structural)renderStructure($('companionStructure'),I.companion,a,b);else{$('companionTitle').textContent=title(I.companion)+' · linked companion';$('companionCaption').textContent=caption+' '+note(I.companion);draw(I.companion,$('companionSvg'),$('companionRateSvg'));}}
 if(['system','lineage'].includes(I.active))renderStructure($('structurePanel'),I.active,a,b);
 applyWorkspace();
 $('cursorReadout').innerHTML=[['a',a],...(b?[['b',b]]:[])].map(([key,z])=>{const v=D.values(z.r),val=k=>v[k]==null?'unavailable':v[k],shift=S.clock==='aligned'&&z.anchor.available?z.anchor.anchor_s:0;return '<strong>'+key.toUpperCase()+' · Event '+z.r.event_index+' · '+esc(z.r.event_kind.replaceAll('_',' '))+'</strong> · '+fmt(z.r.time_s)+' native s'+(S.clock==='aligned'?' / '+(z.anchor.available?fmt(z.r.time_s-shift)+' aligned s':'alignment unavailable'):'')+' · Ready '+val('ready')+' jobs · Unfinished required '+val('unfinished')+' jobs · Configured '+val('rate')+' jobs/tick · Actually completed at this event '+z.r.identities.completed_this_tick.length+' jobs'+(z.r.event_kind==='service_end'?' during the preceding '+z.s.tick_duration_s+' s tick.':' (instantaneous action record).')+'<br>';}).join('');
 $('orderedEvents').innerHTML=[['a',a],...(b?[['b',b]]:[])].map(([key,z])=>'<div class="event-list" aria-label="Ordered events '+key.toUpperCase()+'">'+z.prefix.map(r=>'<button data-cursor-side="'+key+'" data-cursor-event="'+r.event_index+'" aria-pressed="'+(z.r.id===r.id)+'">'+key.toUpperCase()+' e'+r.event_index+' · '+fmt(r.time_s)+' s · '+esc(r.event_kind.replaceAll('_',' '))+'</button>').join('')+'</div>').join('');
 $('orderedEvents').querySelectorAll('button').forEach(el=>el.onclick=()=>select(el.dataset.cursorSide,+el.dataset.cursorEvent));
 if(I.active==='timescale')renderTimescale();
}
function ensureExtensions(){
 const I=S.instrument;
 I.workspace=I.workspace||clone(instrumentDefaults.workspace);
 I.structure=I.structure||clone(instrumentDefaults.structure);
 if(I.calibration){I.calibration.kernelOffset=I.calibration.kernelOffset??0;I.calibration.landscapeVersion=I.calibration.landscapeVersion||'timescale-landscape/1';I.calibration.landscapeCamera=I.calibration.landscapeCamera||{...TimescaleLandscape.defaultCamera};}
 const id=I.structure.selectedIdentity;
 if(id&&(!S.compare&&id.side==='B'||selected(id.side.toLowerCase()).s.case_id!==id.caseId))I.structure.selectedIdentity=null;
}
function drawNumericPlot(type,svg,rateSvg,all,select){
 const I=S.instrument,D=DirectInstruments,container=svg.closest('.resizable-panel');
 const rates=type==='time'?I.timeChannels.filter(k=>D.channels[k].unit==='jobs/tick'):[];
 rateSvg.hidden=!rates.length;rateSvg.toggleAttribute('hidden',!rates.length);
 // Fixed-size panels provide a real plotting budget, not a scaled 900px drawing.
 const primary=container.id==='primaryPanel',bottom=primary?$('timeA').parentElement.getBoundingClientRect().height+$('exactStrip').getBoundingClientRect().height+$('numericStatus').getBoundingClientRect().height:0;
 const box=container.getBoundingClientRect(),top=svg.getBoundingClientRect().top-box.top+container.scrollTop;
 const budget=Math.max(320,box.height-top-bottom-32),rateHeight=rates.length?Math.max(210,Math.round(budget*.27)):0;
 const columns=Math.max(1,Math.floor((svg.getBoundingClientRect().width-80)/220)),count=I.timeChannels.filter(k=>D.channels[k].unit==='jobs').length;
 const minimum=type==='time'?Math.max(320,270+Math.ceil(count/columns)*32):320;
 svg.style.height=Math.max(minimum,budget-rateHeight)+'px';rateSvg.style.height=rateHeight+'px';
 if(all.some(x=>!x.available)){svg.setAttribute('viewBox','0 0 '+Math.max(320,svg.clientWidth)+' '+Math.max(minimum,budget-rateHeight));svg.innerHTML='<text x="20" y="40" font-size="12">Alignment unavailable in this prefix.</text>';rateSvg.innerHTML='';return {};}
 if(type==='time'){const result=D.time(svg,all,{...I,clock:S.clock},select);if(rates.length)D.rate(rateSvg,all,select,rates);return result;}
 return D.relationship(svg,all,I,select);
}
function redrawNumericDimensions(){
 if(!effective)return;
 const I=S.instrument,D=DirectInstruments,a=selected('a'),b=S.compare?selected('b'):null;
 const all=[D.series(a,'a',{...I,clock:S.clock,span:S.span}),...(b?[D.series(b,'b',{...I,clock:S.clock,span:S.span})]:[])],select=(key,index)=>{S[key].eventIndex=index;render();};
 if(['time','relationship'].includes(I.active))drawNumericPlot(I.active,$('numericSvg'),$('rateSvg'),all,select);
 if(!$('companionPanel').hidden&&['time','relationship'].includes(I.companion))drawNumericPlot(I.companion,$('companionSvg'),$('companionRateSvg'),all,select);
}
function applyWorkspace(){
 const w=S.instrument.workspace;LinkedWorkspace.validate(w);
 $('linkedWorkspace').classList.toggle('side',w.arrangement==='side');
 $('linkedWorkspace').classList.toggle('has-companion',!$('companionPanel').hidden);
 $('linkedWorkspace').style.setProperty('--primary-share',w.primaryShare+'%');
 $('primaryPanel').style.height=w.primaryHeight+'px';$('companionPanel').style.height=w.companionHeight+'px';
 $('workspaceArrangement').value=w.arrangement;for(const k of ['primaryHeight','companionHeight','primaryShare'])$(k).value=w[k];
}
$('workspaceArrangement').onchange=e=>{S.instrument.workspace.arrangement=e.target.value;render();};
for(const k of ['primaryHeight','companionHeight','primaryShare'])$(k).onchange=e=>{const next={...S.instrument.workspace,[k]:Number(e.target.value)};try{LinkedWorkspace.validate(next);S.instrument.workspace=next;render();}catch(err){e.target.setCustomValidity(err.message);e.target.reportValidity();}};
for(const k of ['primaryHeight','companionHeight','primaryShare'])$(k).oninput=e=>{e.target.setCustomValidity('');const next={...S.instrument.workspace,[k]:Number(e.target.value)};try{LinkedWorkspace.validate(next);S.instrument.workspace=next;render();}catch(err){/* Incomplete typing is not a committed layout. */}};
$('resetLayout').onclick=()=>{S.instrument.workspace={...LinkedWorkspace.defaults};render();};
for(const [id,key]of [['primaryPanel','primaryHeight'],['companionPanel','companionHeight']]){
 let resizeStart=null;
 $(id).addEventListener('pointerdown',e=>{const box=$(id).getBoundingClientRect();if(e.clientX>box.right-24&&e.clientY>box.bottom-24)resizeStart=true;});
 document.addEventListener('pointerup',()=>{if(!resizeStart)return;resizeStart=null;const n=Math.round($(id).getBoundingClientRect().height),next={...S.instrument.workspace,[key]:n};try{LinkedWorkspace.validate(next);S.instrument.workspace=next;render();}catch(e){render();}});
}
function renderStructure(panel,type,a,b){
 const pref=panel.id,I=S.instrument.structure;
 panel.innerHTML=(type==='lineage'?'<div class="structure-controls"><label>Lineage evidence<select id="'+pref+'Source"><option value="queue">Selected queue record</option><option value="calibration">Selected calibration coefficient</option></select></label><label>Queue feature<select id="'+pref+'Channel">'+Object.entries(DirectInstruments.channels).map(([k,m])=>option(k,m.label)).join('')+'</select></label></div>':'')+'<div class="structure-host"></div>';
 const host=panel.querySelector('.structure-host'),args={A:a,B:b,store:session.store,effective,selectedIdentity:I.selectedIdentity,channelKey:I.lineageChannel,onInspect:openStructureEvidence};
 if(type==='system')StructureUI.renderSystem(host,args);
 else{
  $(pref+'Source').value=I.lineageSource;$(pref+'Channel').value=I.lineageChannel;$(pref+'Channel').disabled=I.lineageSource==='calibration';
  $(pref+'Source').onchange=e=>{I.lineageSource=e.target.value;render();};$(pref+'Channel').onchange=e=>{I.lineageChannel=e.target.value;render();};
  if(I.lineageSource==='calibration')args.coefficient=TimescaleUI.getSelection(S.instrument.calibration);
  StructureUI.renderLineage(host,args);
 }
}
function openStructureEvidence(item){
 const side=(item.side||'A').toLowerCase(),z=selected(side);
 if(item.kind==='identity'){S.instrument.structure.selectedIdentity={side:side.toUpperCase(),caseId:z.s.case_id,identity:item.identity};render();}
 const title=item.kind==='identity'?'Evidence · queue identity '+item.identity:'Evidence · '+(item.detail?.label||item.kind||'structure');
 const d=item.detail||{},identitySummary=item.kind==='identity'?'<div class="identity-focus"><strong>'+esc(item.identity)+' · '+esc(d.case_id)+' · event '+esc(d.selection?.event_index)+'</strong><br>Required: '+esc(d.required)+' · Ready: '+esc(d.ready)+' · FIFO rank: '+esc(d.pending_fifo_rank??'not queued')+'<br>Listed backup copy: '+esc(d.backup_copy)+' · Completed: '+esc(d.completed)+'<br>Required-work disposition: '+esc(d.required_disposition)+'</div>':'';
 openDrawer(title,'<p>'+esc(item.kind==='identity'?'Exact identity selected in the System map and the retained record.':'Source-backed detail from the selected map element.')+'</p>'+identitySummary+'<details open><summary>Exact values and typed relationships</summary><pre>'+esc(pretty(item.detail||item))+'</pre></details>'+(item.record_id?'<h3>Retained record · '+esc(item.record_id)+'</h3><details><summary>Full native record</summary><pre>'+esc(pretty(session.store.resolveRecord(item.record_id)))+'</pre></details>':'')+'<h3>Source drill-down</h3>'+refs(item.pointers||[])+'<p>Source assertions, recorded simulations, derived quantities and rendering choices retain separate types. Unencoded queue evidence remains accessible in All source fields; synthetic calibration is a separate source.</p>','structure');wireRefs();
}
function renderTimescale(){TimescaleUI.render($('timescalePanel'),S.instrument.calibration,render);}
for(const [key,meta]of Object.entries(DirectInstruments.channels)){
 $('xChannel').insertAdjacentHTML('beforeend',option(key,meta.label+' ('+meta.unit+')'));
 $('yChannel').insertAdjacentHTML('beforeend',option(key,meta.label+' ('+meta.unit+')'));
 $('channelChoices').insertAdjacentHTML('beforeend','<label><input type="checkbox" data-channel="'+key+'">'+esc(meta.label)+'</label>');
}
$('inspectCursor').onclick=()=>openEvidence();
for(const el of document.querySelectorAll('[data-view]'))el.onclick=()=>{S.instrument.active=el.dataset.view;render();};
$('companionView').onchange=e=>{S.instrument.companion=e.target.value;render();};
for(const[id,key]of [['xChannel','xChannel'],['yChannel','yChannel']])$(id).onchange=e=>{S.instrument[key]=e.target.value;render();};
$('numericMax').oninput=e=>{if(e.target.value===''||e.target.validity.badInput)return;const n=+e.target.value;if(n>0){S.instrument.yMax=n;render();}};$('numericMax').onchange=e=>{const n=+e.target.value;S.instrument.yMax=e.target.value===''?null:(n>0?n:null);render();};
$('timePan').oninput=e=>{if(e.target.value===''||e.target.validity.badInput)return;S.instrument.timeOffset=Math.min(0,+e.target.value);render();};$('timePan').onchange=e=>{S.instrument.timeOffset=Math.min(0,+e.target.value||0);render();};
$('channelChoices').onchange=()=>{const keys=[...document.querySelectorAll('[data-channel]:checked')].map(el=>el.dataset.channel);if(keys.length)S.instrument.timeChannels=keys;render();};

function linkedPlotHeight(svg){const panel=svg.closest('.linked'),box=panel.getBoundingClientRect(),offset=svg.getBoundingClientRect().top-box.top+panel.scrollTop,height=panel.style.height?Math.max(180,box.height-offset-18):180;svg.style.height=height+'px';return height;}
function drawHistory(a,b){const svg=$('historySvg'),w=Math.max(330,svg.clientWidth),H=linkedPlotHeight(svg),L=42,R=w-20,T=24,bottom=H-32,hh=historyConfig(a,b),min=hh.span[0],max=hh.span[1],X=t=>L+(t-min)/(max-min||1)*(R-L),maxN=effective.linked_views.history.vertical_max_count,Y=n=>bottom-n/Math.max(1,maxN)*(bottom-T),catColors=['#167e85','#bd8434','#925378','#4c8e68'];let s='<title>Prefix-only required-work history, ordered event ribs</title>';for(let i=0;i<=4;i++){const t=min+(max-min)*i/4;s+='<line x1="'+X(t)+'" y1="'+T+'" x2="'+X(t)+'" y2="'+bottom+'" stroke="#e4ebe4"/><text x="'+X(t)+'" y="'+(H-10)+'" text-anchor="middle" font-size="12" fill="#5e756c">'+fmt(t)+'</text>';}s+='<text x="'+L+'" y="14" font-size="12" fill="#5e756c">jobs</text><text x="'+(R-2)+'" y="14" text-anchor="end" font-size="12" fill="#5e756c">'+S.clock+' s</text>';
for(const [key,z,arr]of [['a',a,hh.a],['b',b,hh.b]]){if(!z)continue;for(const [ki,k]of W.categories.entries()){let path='';for(let i=0;i<arr.length;i++){const r=arr[i],t=r.display_time_s;if(t>max)break;const next=arr[i+1]?.display_time_s??t;if(next<min)continue;const x=X(Math.max(t,min)),y=Y(r.weights[k.key]);path+=(path?'L':'M')+x+' '+y;if(next>=t)path+='L'+X(Math.min(next,max))+' '+y;}s+='<path d="'+path+'" fill="none" stroke="'+catColors[ki]+'" stroke-width="'+(key==='a'?2:1.4)+'" '+(key==='b'?'stroke-dasharray="4 3"':'')+'/>';}
for(const r of arr.filter(r=>r.row_kind!=='carry_in'&&r.display_time_s>=min&&r.display_time_s<=max)){const x=X(r.display_time_s),offset=r.event_index===0?-4:r.event_index===1?4:0;s+='<g data-history-key="'+key+'" data-event="'+r.event_index+'" tabindex="0" role="button" aria-label="Select '+key.toUpperCase()+' event '+r.event_index+'" style="cursor:pointer"><line x1="'+x+'" y1="'+T+'" x2="'+x+'" y2="'+bottom+'" stroke="'+(key==='a'?'#237a82':'#b27b31')+'" stroke-opacity=".2"/><circle cx="'+(x+offset)+'" cy="'+(key==='a'?bottom+2:T)+'" r="5" fill="'+(key==='a'?'#237a82':'white')+'" stroke="'+(key==='a'?'#237a82':'#b27b31')+'"/><title>Event '+r.event_index+' at '+fmt(r.time_s)+' native s; marker offset only distinguishes same-time order</title></g>';}}
svg.setAttribute('viewBox','0 0 '+w+' '+H);svg.innerHTML=s;svg.querySelectorAll('[data-event]').forEach(g=>{const f=()=>{S[g.dataset.historyKey].eventIndex=+g.dataset.event;render();};g.onclick=f;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();f();}};});$('historyCaption').textContent='Ready / backup-only / absent / completed · A solid, B dashed. Each side is clipped to its own trailing window before sharing this axis. Carry-in is a model-held state, not a new event. '+windowCaption(hh);}
function drawProfile(a,b){const svg=$('profileSvg'),w=Math.max(330,svg.clientWidth),H=linkedPlotHeight(svg),L=48,R=w-20,T=24,bot=H-32,min=-3.6,max=3.6;const ymax=effective.linked_views.transverse.vertical_max_density,X=u=>L+(u-min)/(max-min)*(R-L),Y=f=>bot-f/ymax*(bot-T);let s='<title>Section through the exact spatial rendering function</title>';for(let i=-3;i<=3;i++){s+='<line x1="'+X(i)+'" y1="'+T+'" x2="'+X(i)+'" y2="'+bot+'" stroke="#e5ece5"/><text x="'+X(i)+'" y="'+(H-10)+'" text-anchor="middle" font-size="12" fill="#63766a">'+i+'</text>';}
s+='<text x="3" y="'+T+'" font-size="12" fill="#63766a">'+fmt(ymax)+'</text><text x="19" y="'+bot+'" font-size="12" fill="#63766a">0</text>';for(const[z,c,dash]of [[a,'#0d7e84',false],[b,'#b77926',true]]){if(!z)continue;let p='';for(let i=0;i<effective.linked_views.transverse.curve_samples;i++){const q=min+(max-min)*i/(effective.linked_views.transverse.curve_samples-1);const f=S.slice.axis==='u'?W.field(q,S.slice.offset,z.p.weights,S.h):W.field(S.slice.offset,q,z.p.weights,S.h);p+=(i?'L':'M')+X(q)+' '+Y(f);}s+='<path d="'+p+'" fill="none" stroke="'+c+'" stroke-width="2" '+(dash?'stroke-dasharray="5 3"':'')+'/>';}svg.setAttribute('viewBox','0 0 '+w+' '+H);svg.innerHTML=s;}
function openDrawer(title,html,kind){lastFocus=document.activeElement;drawerKind=kind;$('drawerTitle').textContent=title;$('drawerBody').innerHTML=html;$('drawerBackdrop').classList.add('open');document.body.style.overflow='hidden';$('closeDrawer').focus();}
function closeDrawer(){$('drawerBackdrop').classList.remove('open');document.body.style.overflow='';drawerKind=null;lastFocus?.focus?.();}
function ptrValue(p){const r=session.store.resolvePointer(p);if(r.status!=='resolved')throw Error(r.status+': '+p);return r.value;}
function refs(refs){return [...new Set(refs)].map(p=>'<button class="pointer" data-pointer="'+esc(p)+'">'+esc(p||'(root)')+'</button>').join(' ');}
function wireRefs(){$('drawerBody').querySelectorAll('[data-pointer]').forEach(el=>el.onclick=()=>openSourceNode(el.dataset.pointer));}
function identityText(ids,side){const focus=S.instrument.structure.selectedIdentity;return ids.length?ids.map(id=>focus&&focus.side===side.toUpperCase()&&focus.caseId===selected(side).s.case_id&&focus.identity===id?'<mark title="Selected in System map">'+esc(id)+'</mark>':esc(id)).join(', '):'none';}
function openEvidence(category){const sides=['a',...(S.compare?['b']:[])];openDrawer(category?W.categories.find(k=>k.key===category).label+' · exact identities':'Evidence / native values','<p>The body encodes required-work disposition only. Similar shapes can have different actions, identities, rates, backups and histories. These remain in the native record.</p><div class="evidence-grid">'+sides.map(key=>{const z=selected(key);return '<div class="evidence-side '+key+'"><h3>'+key.toUpperCase()+' · '+esc(DisplayLabels.caseLabel(bundle,z.s.case_id).label)+'</h3><p>'+esc(z.r.event_kind)+' · '+z.r.time_s+' native s · event '+z.r.event_index+'<br>Configured '+z.r.values.rate+' jobs/tick · deadline '+z.s.deadline_s+' s<br>'+esc(DisplayLabels.worldLabel(z.w).label)+(z.w.uncertainty.actual_rate_unknown?' · actual rate unresolved':' · stipulated model')+'</p><table><tr><th>Disposition</th><th>Count / required identities</th></tr>'+W.categories.filter(k=>!category||k.key===category).map(k=>'<tr><td>'+k.label+'</td><td><strong>'+z.p.weights[k.key]+'</strong> · '+identityText(z.p.identities[k.key],key)+'</td></tr>').join('')+'</table><h3>Numeric values at this event</h3><table>'+Object.entries(SourceChannels.record(z.r).channels).map(([k,c])=>'<tr><td>'+esc(c.label)+'</td><td>'+esc(c.value==null?'Not applicable / unavailable':c.value)+' '+esc(c.unit)+'</td></tr>').join('')+'</table><h3>Selected action</h3><p>'+esc(DisplayLabels.actionLabel(z.s).label)+'</p><h3>Technical details · '+esc(z.s.id)+'</h3><pre>'+esc(pretty(z.s.action))+'</pre><details><summary>Full native record and units</summary><pre>'+esc(pretty({record:z.r,units:bundle.metadata.channel_units}))+'</pre></details><h3>Source drill-down</h3>'+refs(z.r.source_refs)+'</div>';}).join('')+'</div><h3>Not encoded by the surface</h3><p>FIFO order, identity names, backup-copy relationships after completion, configured rate, service offered, pause duration, deadline, action cost, uncertainty and source metadata are not geometrically recoverable. Six sensor cases are preserved and unaligned.</p>','evidence');wireRefs();}
function openSourceNode(pointer){const row=bundle.ledger.find(r=>r.pointer===pointer);openDrawer('Source field','<button id="backSources">← All source fields</button><h3>'+esc(pointer||'(root)')+'</h3><p>Geometry use: selected required-identity membership is derived through the event model. Other source detail remains outside the four-weight surface. Original ledger usage labels refer to the preserved earlier trace viewer.</p><pre>'+esc(pretty({original:ptrValue(pointer),preserved_ledger:row,source_sha256:bundle.source.sha256}))+'</pre>','source');$('backSources').onclick=openSources;}
function openSources(){openDrawer('All retained source fields','<p>'+bundle.ledger.length+' source nodes remain accessible. This view has four derived weights, not a lossless encoding of every field. Original ledger dispositions are preserved verbatim.</p><button id="rawDownload">Download original source bytes</button><input id="sourceSearch" type="search" aria-label="Search retained source fields" placeholder="Search a pointer, value, identity or status"><div id="sourceResults"></div>','sources');const fill=()=>{const q=$('sourceSearch').value.toLowerCase(),rows=bundle.ledger.filter(r=>JSON.stringify(r).toLowerCase().includes(q));$('sourceResults').innerHTML='<p>'+rows.length+' matches · first 100 shown; search to narrow</p><table><tr><th>Pointer</th><th>Native typed value</th></tr>'+rows.slice(0,100).map(r=>'<tr><td><button class="pointer" data-pointer="'+esc(r.pointer)+'">'+esc(r.pointer||'(root)')+'</button></td><td>'+esc(r.number_lexeme??JSON.stringify(r.value).slice(0,180))+'<br><small>'+esc(r.type)+' · '+esc(r.structural_status)+'</small></td></tr>').join('')+'</table>';wireRefs();};$('sourceSearch').oninput=fill;$('rawDownload').onclick=()=>download(Uint8Array.from(atob(bundle.source.raw_base64),c=>c.charCodeAt(0)),'cases-original.json','application/json');fill();}
function instrumentRendering(e){
 const I=e.requested.instrument;if(!I?.workspace||!I?.calibration?.landscapeVersion)return null;
 const c=TimescaleUI.getSelection(I.calibration);
 return {version:'linked-rendering-record/1',workspace:LinkedWorkspace.describe(I.workspace),timescale:TimescaleLandscape.renderingRecord(c.result,{camera:I.calibration.landscapeCamera,row:c.support.scale_index,sample:c.support.sample_index}),kernel_inspection_version:CanonTimescale.kernelInspectionVersion,scope:'Configured rendering from the effective recipe. Viewport-independent transformation record; runtime canvas dimensions adapt to the saved layout and current window.'};
}
function getManifest(){const saved=session.save(effective,{checkpointId:checkpointId||'unsaved-preview',parentId:parentCheckpoint,renderingRecord:scene.manifest()});const record=instrumentRendering(effective);if(record)saved.instrument_rendering=record;return saved;}
function windowCaption(hh){const f=(label,frame)=>frame&&frame.status==='available'?label+' ['+frame.nativeWindow.map(fmt).join(', ')+'] native s; '+frame.displayWindow.map(fmt).join(' → ')+' display s.':'';return f('A',effective.observation.A)+' '+f('B',effective.observation.B);}

function download(content,name,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function restore(manifest){const restored=session.restore(manifest);if(manifest.instrument_rendering&&AnalyticSession.stable(instrumentRendering(restored.effective))!==AnalyticSession.stable(manifest.instrument_rendering))throw Error('Saved instrument rendering record disagrees with the effective recipe.');delete S.instrument;Object.assign(S,restored.state);checkpointId=restored.checkpoint.id;parentCheckpoint=restored.checkpoint.parent_id;render();}
function openManifest(){openDrawer('Effective configuration / transformations','<p>Shared calibration applies to both bodies. Camera, time, registration, coordinates, scale and spatial softness are recorded separately. Finite surface cropping and viewport clipping do not change the exact weights.</p><button id="drawerExport">Download this view</button><pre>'+esc(pretty(getManifest()))+'</pre>','manifest');$('drawerExport').onclick=()=>download(pretty(getManifest()),'canon-state-body-view.json');}
function openExport(){parentCheckpoint=checkpointId;checkpointId='checkpoint:'+new Date().toISOString();const text=pretty(getManifest());openDrawer('Export this exact view','<p>This JSON records the selected events, source hash, shared calibration, anchors, crop, camera and rendering settings. Download it or select and copy the text. Restore accepts either a saved file or pasted JSON.</p><button id="downloadView">Download JSON</button><textarea id="exportText" aria-label="Exported view JSON" readonly spellcheck="false">'+esc(text)+'</textarea>','export');$('downloadView').onclick=()=>download(text,'canon-state-body-view.json');}
function openRestore(){openDrawer('Restore a saved view','<p>Sources, adapter, frame, encoding, kernel, renderer and session versions must match. Replay recomputes the effective configuration; unsupported versions or missing sources are rejected visibly. Paste exported JSON below, or choose a saved file.</p><button id="chooseViewFile">Choose JSON file</button><textarea id="restoreText" aria-label="View JSON to restore" spellcheck="false" placeholder="Paste an exported view here"></textarea><button id="applyRestore" class="primary">Restore this view</button><p id="restoreError" role="alert"></p>','restore');$('chooseViewFile').onclick=()=>$('importFile').click();$('applyRestore').onclick=()=>{try{restore(JSON.parse($('restoreText').value));closeDrawer();}catch(e){$('restoreError').textContent=e.message;}};}
const examples=[['V01','Replay versus waiting','T4M6/A',1,'T4M6/B',1],['V02','Compare missing-copy and backup cases','H9C3/B','end','T4M6/B','end'],['V03','Same selected view, different provenance','D8V1/C',2,'T4M6/A',2],['V04','Separate service-rate alternatives','P5J9/A','end','P5J9/A','end'],['V05','Compare actions under the two-second deadline','B2R8/B','end','B2R8/C','end']];
function loadExample(i){const e=examples[i];for(const [key,id,idx]of [['a',e[2],e[3]],['b',e[4],e[5]]]){const s=scenarios.get(id),wi=i===3&&key==='b'?1:0;S[key]={scenarioId:id,worldIndex:wi,eventIndex:idx==='end'?s.worlds[wi].records.at(-1).event_index:idx,anchor:'decision'};}S.compare=true;S.mode='overlay';S.perspective='now';S.clock='native';closeDrawer();render();}
function openExamples(){openDrawer('Five visual inspections','<p>These are already specified synthetic fixture behaviors. Each loads two independent records under shared calibration.</p>'+examples.map((e,i)=>'<p style="margin-top:14px"><button data-example="'+i+'">'+e[0]+' · '+e[1]+'</button></p>').join(''),'examples');$('drawerBody').querySelectorAll('[data-example]').forEach(el=>el.onclick=()=>loadExample(+el.dataset.example));}
for(const key of ['a','b']){const u=key.toUpperCase();$('case'+u).onchange=e=>chooseCase(key,e.target.value);$('action'+u).onchange=e=>chooseAction(key,e.target.value);$('world'+u).onchange=e=>{S[key].worldIndex=+e.target.value;S[key].eventIndex=Math.min(S[key].eventIndex,selected(key).w.records.at(-1).event_index);render();};$('anchor'+u).onchange=e=>{S[key].anchor=e.target.value;render();};}
$('compareToggle').onclick=()=>{S.compare=!S.compare;render();};$('nowMode').onclick=()=>{S.perspective='now';render();};$('historyMode').onclick=()=>{S.perspective='history';render();};document.querySelectorAll('[data-mode]').forEach(el=>el.onclick=()=>{S.mode=el.dataset.mode;render();});$('blinkButton').onclick=()=>{blinkSide=blinkSide==='A'?'B':'A';S.mode='solo'+blinkSide;render();};$('fitCamera').onclick=()=>{scene.fitBoth();S.camera=scene.getCamera();render();};$('frameDemo').onclick=()=>{for(const [key,id] of [['a','B2R8/A'],['b','B2R8/C']]){const w=scenarios.get(id).worlds[0];S[key]={scenarioId:id,worldIndex:0,eventIndex:w.records.at(-1).event_index,anchor:'first_completed_payload'};}S.compare=true;S.mode='overlay';S.perspective='history';S.clock='native';S.span=1;render();scene.fitBoth();};$('homeCamera').onclick=()=>{scene.home();S.camera=scene.getCamera();render();};$('topCamera').onclick=()=>{scene.setCamera({pitch:Math.PI/2,yaw:0,projection:'orthographic'});S.camera=scene.getCamera();render();};$('frontCamera').onclick=()=>{scene.setCamera({pitch:.2,yaw:0,projection:'orthographic'});S.camera=scene.getCamera();render();};$('projection').onchange=e=>{scene.setCamera({projection:e.target.value});S.camera=scene.getCamera();render();};
for(const[id,k]of [['historySpan','span'],['softness','h'],['valueGain','valueGain']])$(id).oninput=e=>{S[k]=+e.target.value;render();};$('clockMode').onchange=e=>{S.clock=e.target.value;render();};for(const[id,k]of [['surfaceToggle','surface'],['contourToggle','contours'],['exactToggle','exact']])$(id).onchange=e=>{S.layers[k]=e.target.checked;render();};$('sliceAxis').onchange=e=>{S.slice.axis=e.target.value;render();};$('sliceOffset').oninput=e=>{S.slice.offset=+e.target.value;render();};
$('evidenceButton').onclick=()=>openEvidence();$('sourceButton').onclick=openSources;$('manifestButton').onclick=openManifest;$('findingsButton').onclick=openExamples;$('exportButton').onclick=()=>download(pretty(getManifest()),'canon-state-body-view.json');$('importButton').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{try{const f=e.target.files[0];if(f)restore(JSON.parse(await f.text()));}catch(err){$('error').textContent=err.message;$('error').style.display='block';}e.target.value='';};$('closeDrawer').onclick=closeDrawer;$('drawerBackdrop').onclick=e=>{if(e.target===$('drawerBackdrop'))closeDrawer();};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer();if($('drawerBackdrop').classList.contains('open')&&e.key==='Tab'){const nodes=[...$('drawerBackdrop').querySelectorAll('button,input,select,summary,[tabindex="0"]')].filter(x=>!x.disabled),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
$('exportButton').onclick=openExport;$('importButton').onclick=openRestore;
new ResizeObserver(()=>render()).observe($('historySvg'));
new ResizeObserver(()=>render()).observe($('bodyCanvas'));
let numericResizeFrame=null;
const numericResize=new ResizeObserver(()=>{if(numericResizeFrame!==null)cancelAnimationFrame(numericResizeFrame);numericResizeFrame=requestAnimationFrame(()=>{numericResizeFrame=null;redrawNumericDimensions();});});
for(const id of ['primaryPanel','companionPanel','numericPanel','companionNumeric'])numericResize.observe($(id));
const linkedResize=new ResizeObserver(()=>{if(!effective||S.instrument.active!=='body')return;const a=selected('a'),b=S.compare?selected('b'):null;if(S.clock!=='aligned'||a.anchor.available&&(!b||b.anchor.available))drawHistory(a,b);drawProfile(a,b);});
for(const panel of document.querySelectorAll('.lower .linked'))linkedResize.observe(panel);
render();
})();
