/* Direct numeric instruments. Nothing here samples SpatialEncoding or its mesh. */
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./channels.js'):root.SourceChannels,typeof module==='object'&&module.exports?require('./frames.js'):root.ObservationFrames);if(typeof module==='object'&&module.exports)module.exports=api;root.DirectInstruments=api;})(typeof globalThis!=='undefined'?globalThis:this,(SourceChannels,Frames)=>{
'use strict';
const version='direct-instruments/1';
const channels={ready:{label:'Ready jobs',unit:'jobs',color:'#087d88'},unfinished:{label:'Unfinished required jobs',unit:'jobs',color:'#ac5078'},completed:{label:'Completed jobs',unit:'jobs',color:'#428054'},backup:{label:'Jobs available only in backup',unit:'jobs',color:'#ad721d'},absent:{label:'Jobs with no listed copy',unit:'jobs',color:'#ba492e'},rate:{label:'Processing rate (configured)',unit:'jobs/tick',color:'#6253b6'},delivered:{label:'Actual completions per service tick',unit:'jobs/tick',color:'#b04e27'}};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>Number.isInteger(x)?String(x):Number(x).toFixed(2).replace(/0+$/,'').replace(/\.$/,'');
function values(r){return SourceChannels.record(r).values;}
function series(z,key,{clock='native',span=4,timeOffset=0}={}){
 const frame=Frames.side(z,{clock,span,timeOffset});
 if(frame.status!=='available')return {key,z,available:false,rows:[],events:[]};
 const byId=new Map(z.prefix.map(r=>[r.id,r])),derived=SourceChannels.fromFrame(z,frame);
 const rows=derived.rows.map(row=>({r:byId.get(row.record_id),carry:row.carry_in,time:row.display_time_s,v:row.carry_in?{...row.values,delivered:null}:row.values,channelRecord:row}));
 return {key,z,available:true,frame,rows,events:rows.filter(x=>!x.carry),start:frame.displayWindow[0],end:frame.displayWindow[1],nativeStart:frame.nativeWindow[0],nativeEnd:frame.nativeWindow[1],shift:frame.shift_s,deadline:z.s.deadline_s-frame.shift_s,action:-frame.shift_s,pauseEnd:(z.s.action.parameters.pause_ticks||0)*z.s.tick_duration_s-frame.shift_s};
}
function range(series,keys){return Math.ceil(Math.max(1,...series.flatMap(s=>(s.z?.prefix?s.z.prefix.map(r=>({v:values(r)})):s.rows).flatMap(row=>keys.map(k=>row.v[k]??0))))/4)*4;}
// Geometry uses CSS pixels; native values and shared ranges never depend on size.
// Non-DOM callers retain the original reference geometry for compatibility.
function geometry(svg,kind,legendCount=0){
 const fallback={time:{W:900,H:430,L:65,R:870,T:37,B:280},rate:{W:900,H:170,L:65,R:870,T:25,B:95},relationship:{W:900,H:400,L:75,R:850,T:38,B:320}}[kind];
 const box=svg.getBoundingClientRect?.();if(!box||box.width<=0||box.height<=0)return {...fallback,responsive:false};
 const W=Math.max(320,Math.round(box.width)),columns=Math.max(1,Math.floor((W-80)/220)),legendRows=Math.ceil(legendCount/columns),H=Math.max(kind==='rate'?200:320,Math.round(box.height));
 return {W,H,L:62,R:W-26,T:kind==='rate'?57:54,B:H-(kind==='time'?125+legendRows*32:kind==='rate'?91:75),columns,responsive:true};
}
function words(text,width){const limit=Math.max(12,Math.floor(width/6.6)),lines=[];let line='';for(const word of text.split(' ')){if(line&&(line+' '+word).length>limit){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);return lines;}
function textLines(text,x,y,width,anchor='start',color='currentColor'){return `<text x="${x}" y="${y}" text-anchor="${anchor}" fill="${color}" font-size="12">`+words(text,width).map((line,i)=>`<tspan x="${x}" dy="${i?14:0}">${esc(line)}</tspan>`).join('')+'</text>';}
function grid(L,R,T,B,maxX,maxY,xf,yf,xLabel,yLabel,responsive=false){let s='';for(let i=0;i<=4;i++){const x=maxX[0]+(maxX[1]-maxX[0])*i/4,y=maxY*i/4;s+=`<path d="M${xf(x)} ${T}V${B}M${L} ${yf(y)}H${R}" stroke="#dce5e2"/><text x="${xf(x)}" y="${B+20}" text-anchor="middle">${fmt(x)}</text><text x="${L-9}" y="${yf(y)+4}" text-anchor="end">${fmt(y)}</text>`;}if(responsive)return s+textLines(yLabel,L,16,R-L)+textLines(xLabel,R,B+42,R-L,'end');return s+`<text x="${L}" y="${T-14}">${esc(yLabel)}</text><text x="${R}" y="${B+42}" text-anchor="end">${esc(xLabel)}</text>`;}
function handle(side,row,x,y,selected,extra=''){return `<g class="event-point" data-side="${side}" data-event="${row.r.event_index}" tabindex="0" role="button" aria-label="Select ${side.toUpperCase()} event ${row.r.event_index}" data-record="${esc(row.r.id)}"><circle cx="${x}" cy="${y}" r="${selected?7:4.5}" fill="${side==='a'?'#fff':'#fff2df'}" stroke="${selected?'#142f3d':side==='a'?'#067b86':'#a56b20'}" stroke-width="${selected?3:1.5}"/><title>${side.toUpperCase()} · event ${row.r.event_index} · ${row.r.event_kind.replaceAll('_',' ')} · ${fmt(row.r.time_s)} native s. ${extra}</title></g>`;}
function wire(svg,select){svg.querySelectorAll('[data-event]').forEach(el=>{const run=()=>select(el.dataset.side,+el.dataset.event);el.onclick=run;el.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();run();}};});}
function time(svg,all,settings,select){const keys=settings.timeChannels,counts=keys.filter(k=>channels[k].unit==='jobs'),rates=keys.filter(k=>channels[k].unit!=='jobs'),g=geometry(svg,'time',counts.length),{W,H,L,R,T,B}=g,domain=[Math.min(...all.map(x=>x.start)),Math.max(...all.map(x=>x.end))],X=x=>L+(x-domain[0])/(domain[1]-domain[0]||1)*(R-L),cap=settings.yMax||range(all,counts),Y=y=>B-y/cap*(B-T);let s=`<title>Over time: source-derived counts, ordered events</title><defs><clipPath id="timeClip${svg.id}"><rect x="${L}" y="${T}" width="${R-L}" height="${B-T}"/></clipPath></defs>`+grid(L,R,T,B,domain,cap,X,Y,settings.clock==='aligned'?'Event-relative time (seconds)':'Native time (seconds)','Jobs · shared A/B range',g.responsive);
 let i=0;for(const k of counts){s+=g.responsive?textLines(channels[k].label,L+(i%g.columns)*(R-L)/g.columns,B+113+Math.floor(i/g.columns)*32,(R-L)/g.columns-10,'start',channels[k].color):`<text x="${L+(i%3)*270}" y="${H-27+Math.floor(i/3)*17}" fill="${channels[k].color}">${esc(channels[k].label)}</text>`;i++;}
 for(const a of all){const color=a.key==='a'?'#087d88':'#ac7529',stroke=a.key==='b'?' stroke-dasharray="6 4"':'';
 s+=`<g clip-path="url(#timeClip${svg.id})">`;
 if(a.pauseEnd>a.action){const x1=X(Math.max(a.start,a.action)),x2=X(Math.min(a.end,a.pauseEnd));if(x2>x1)s+=`<rect x="${x1}" y="${T}" width="${x2-x1}" height="${B-T}" fill="${color}" opacity=".07"/>`;}
 for(const k of counts){let d='';for(let n=0;n<a.rows.length;n++){const p=a.rows[n],next=a.rows[n+1];if(p.v[k]==null){continue;}const x=X(p.time),y=Y(p.v[k]);d+=((n>0&&a.rows[n-1].v[k]!=null)?'L':'M')+x+' '+y;d+='H'+X(next?next.time:a.end);}s+=`<path d="${d}" fill="none" stroke="${channels[k].color}" stroke-width="2"${stroke}/>`;}
 for(const p of a.events){s+=`<path d="M${X(p.time)} ${T}V${B}" stroke="${color}" opacity=".12"/>`;for(const k of counts)if(p.v[k]!=null)s+=handle(a.key,p,X(p.time),Y(p.v[k]),p.r.id===a.z.r.id,channels[k].label+': '+p.v[k]+' jobs');}
 for(const[t,label]of [[a.action,'Action'],[a.deadline,'Original deadline']])if(t>=a.start&&t<=a.end)s+=`<path d="M${X(t)} ${T}V${B}" stroke="${color}" stroke-dasharray="3 5"/><text x="${Math.min(R-120,X(t)+5)}" y="${a.key==='a'?T+13:T+29}" fill="${color}">${a.key.toUpperCase()} ${label}</text>`;
 s+='</g>';
 // Same-time handles live on an event rail: no alteration to numeric coordinates.
 for(const p of a.events){const duplicates=a.events.filter(q=>q.time===p.time),j=duplicates.indexOf(p),dx=(j-(duplicates.length-1)/2)*17;s+=handle(a.key,p,X(p.time)+dx,a.key==='a'?B+61:B+79,p.r.id===a.z.r.id,'Ordered event rail; horizontal handle offset is presentation only.');}
 }
 svg.setAttribute('viewBox',`0 0 ${W} ${H}`);if(g.responsive){svg.style.height=H+'px';svg.setAttribute('data-plot-bounds',JSON.stringify({left:L,right:R,top:T,bottom:B}));svg.setAttribute('data-calibration',JSON.stringify({yMax:typeof cap==='number'?cap:my,xRange:typeof domain!=='undefined'?domain:[0,mx]}));}svg.innerHTML=s;wire(svg,select);
 return {domain,cap,rates,clipped:all.some(a=>a.rows.some(p=>counts.some(k=>p.v[k]>cap)))};
}
function rate(svg,all,select,keys=['rate']){const g=geometry(svg,'rate'),{W,H,L,R,T,B}=g,domain=[Math.min(...all.map(x=>x.start)),Math.max(...all.map(x=>x.end))],cap=range(all,keys),X=x=>L+(x-domain[0])/(domain[1]-domain[0]||1)*(R-L),Y=y=>B-y/cap*(B-T);let s=grid(L,R,T,B,domain,cap,X,Y,'Same time axis (seconds)','Jobs/tick · configured capacity / actual completions',g.responsive);for(const a of all){for(const k of keys){if(k==='rate'){let d='',prior=false;for(let n=0;n<a.rows.length;n++){const p=a.rows[n];if(p.v[k]==null){prior=false;continue;}d+=(prior?'L':'M')+X(p.time)+' '+Y(p.v[k])+'H'+X(a.rows[n+1]?.time??a.end);prior=true;}s+=`<path d="${d}" fill="none" stroke="${channels[k].color}" stroke-width="2" ${a.key==='b'?'stroke-dasharray="6 4"':''}/>`;}for(const p of a.events)if(p.v[k]!=null)s+=handle(a.key,p,X(p.time),Y(p.v[k]),p.r.id===a.z.r.id,channels[k].label+': '+p.v[k]+' jobs/tick');}}s+=g.responsive?textLines('Configured rate: steps. Actual completions: service-event dots; absent at action records.',L,B+66,R-L):'<text x="65" y="164">Configured rate is a step; actual completions are service-event dots, never imputed at action records.</text>';svg.setAttribute('viewBox',`0 0 ${W} ${H}`);if(g.responsive){svg.style.height=H+'px';svg.setAttribute('data-plot-bounds',JSON.stringify({left:L,right:R,top:T,bottom:B}));svg.setAttribute('data-calibration',JSON.stringify({yMax:typeof cap==='number'?cap:my,xRange:typeof domain!=='undefined'?domain:[0,mx]}));}svg.innerHTML=s;wire(svg,select);}
function relationship(svg,all,settings,select){const g=geometry(svg,'relationship'),{W,H,L,R,T,B}=g,kx=settings.xChannel,ky=settings.yChannel,mx=range(all,[kx]),my=settings.yMax||range(all,[ky]),X=x=>L+x/mx*(R-L),Y=y=>B-y/my*(B-T),marker='arrow'+svg.id;let s=`<title>Relationship: discrete paired source channels</title><defs><marker id="${marker}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10" fill="#79928e"/></marker><clipPath id="xyClip${svg.id}"><rect x="${L-10}" y="${T}" width="${R-L+20}" height="${B-T+10}"/></clipPath></defs>`+grid(L,R,T,B,[0,mx],my,X,Y,channels[kx].label+' ('+channels[kx].unit+')',channels[ky].label+' ('+channels[ky].unit+')',g.responsive);
 s+=`<g clip-path="url(#xyClip${svg.id})">`;for(const a of all){const color=a.key==='a'?'#0b7f88':'#af792b';for(let i=1;i<a.rows.length;i++){const p=a.rows[i-1],q=a.rows[i];if([p.v[kx],q.v[kx],p.v[ky],q.v[ky]].every(v=>v!=null)&&(p.v[kx]!==q.v[kx]||p.v[ky]!==q.v[ky]))s+=`<path d="M${X(p.v[kx])} ${Y(p.v[ky])}L${X(q.v[kx])} ${Y(q.v[ky])}" fill="none" stroke="${color}" stroke-width="1.5" marker-end="url(#${marker})" ${a.key==='b'?'stroke-dasharray="5 4"':''}/>`;}
 for(const p of a.rows){if(p.v[kx]==null||p.v[ky]==null)continue;const coincident=a.rows.filter(q=>q.v[kx]===p.v[kx]&&q.v[ky]===p.v[ky]),dwell=coincident.reduce((sum,q)=>{const idx=a.rows.indexOf(q);return sum+Math.max(0,(a.rows[idx+1]?.time??a.end)-q.time);},0);if(!p.carry)s+=handle(a.key,p,X(p.v[kx]),Y(p.v[ky]),p.r.id===a.z.r.id,`(${p.v[kx]}, ${p.v[ky]}); ${[kx,ky].includes('delivered')?'Service-event measurement; no dwell inferred.':'retained dwell '+fmt(dwell)+' s.'} Coincident events selectable below.`);}
 const grouped=new Map();for(const p of a.rows){if(p.v[kx]==null||p.v[ky]==null)continue;const key=p.v[kx]+','+p.v[ky];if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(p);}for(const group of grouped.values()){const p=group[0],dwell=group.reduce((sum,q)=>sum+Math.max(0,(a.rows[a.rows.indexOf(q)+1]?.time??a.end)-q.time),0);s+=`<text x="${Math.min(R-60,X(p.v[kx])+11)}" y="${Y(p.v[ky])+(a.key==='a'?-12:22)}" fill="${color}">${a.key.toUpperCase()} e${group.map(q=>q.r.event_index).join(',')}${g.responsive?'':' @'+fmt(p.r.time_s)+'s'+([kx,ky].includes('delivered')?' · event value':' · held '+fmt(dwell)+'s')}</text>`;}}
 s+='</g>';svg.setAttribute('viewBox',`0 0 ${W} ${H}`);if(g.responsive){svg.style.height=H+'px';svg.setAttribute('data-plot-bounds',JSON.stringify({left:L,right:R,top:T,bottom:B}));svg.setAttribute('data-calibration',JSON.stringify({yMax:typeof cap==='number'?cap:my,xRange:typeof domain!=='undefined'?domain:[0,mx]}));}svg.innerHTML=s;wire(svg,select);return {clipped:all.some(a=>a.rows.some(p=>p.v[ky]>my))};}
return Object.freeze({version,channels,values,series,time,rate,relationship,range,geometry});
});
