/* Linked, inspectable structure and lineage SVG views. */
(function(root,factory){const node=typeof module==='object'&&module.exports;const api=factory(node?require('./structure.js'):root.SystemStructure);if(node)module.exports=api;if(root)root.StructureUI=api;})(typeof globalThis!=='undefined'?globalThis:this,S=>{
'use strict';
const version='system-lineage/1';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=`<style>.structure-view{color:#183c41}.structure-view h2{font-size:21px;margin:8px 0}.structure-view h3{font-size:18px;margin:10px 0}.structure-note{font-size:14px;line-height:1.45;color:#456168;margin:7px 0}.structure-card{border:1px solid #c7d8d3;background:#fbfdfb;border-radius:12px;padding:15px;margin:12px 0}.structure-svg{width:100%;display:block;min-width:700px;font-family:Segoe UI,Arial,sans-serif}.structure-scroll{overflow-x:auto}.structure-svg [role=button]{cursor:pointer}.structure-svg [role=button]:focus{outline:none;filter:drop-shadow(0 0 3px #a53f7a)}.structure-legend{display:flex;gap:15px;flex-wrap:wrap;font-size:13px}.structure-legend span{border-left:4px solid var(--line);padding-left:7px}.structure-claim{font-size:13px;margin-top:10px}.structure-claim summary{cursor:pointer}.structure-detail{max-height:360px;overflow:auto;white-space:pre-wrap}.lineage-tags{display:flex;gap:10px;flex-wrap:wrap;font-size:13px}.lineage-tags span{padding:4px 7px;border:1px solid #cbd8d6;border-radius:5px}</style>`;
const colors={required:'#738384',ready_fifo:'#097f91',backup_copy:'#985ab4',completed:'#3b865b',no_listed_copy:'#b35d3e',constrains:'#81928d'};
function inspectionPayload(graph,item,kind){
 return {kind,side:graph.selection?.side||null,caseId:graph.selection?.case_id||null,identity:item.identity||null,
  record_id:graph.selection?.record_id||null,source_revision:graph.selection?.source_revision||graph.source_revision||null,
  pointers:(item.source_refs||[]).map(ref=>ref.pointer).filter(Boolean),source_refs:item.source_refs||[],record_refs:item.record_refs||[],
  detail:kind==='identity'?{...item.detail,selection:graph.selection,relations:graph.edges.filter(e=>e.from===item.id||e.to===item.id),source_record_refs:item.record_refs}:item};
}
function wire(container,graph,onInspect){
 const payload=(item,kind)=>inspectionPayload(graph,item,kind);
 const show=data=>{if(onInspect)onInspect(data);else{const pre=container.querySelector('.structure-detail');if(pre){pre.hidden=false;pre.textContent=JSON.stringify(data,null,2);}}};
 container.querySelectorAll('[data-node]').forEach(el=>{const item=graph.nodes[+el.dataset.node],kind=item.kind==='identity'?'identity':item.kind==='rule'?'constraint':'lineage';const run=()=>show(payload(item,kind));el.onclick=run;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();run();}};});
 container.querySelectorAll('[data-edge]').forEach(el=>{const item=graph.edges[+el.dataset.edge],run=()=>show(payload(item,'relation'));el.onclick=run;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();run();}};});
}
function systemSvg(graph,selectedIdentity){
 const identities=graph.nodes.filter(n=>n.kind==='identity'),rules=graph.nodes.filter(n=>n.kind==='rule'),h=Math.max(420,identities.length*55+60),height=h+200,positions=new Map();
 graph.nodes.forEach((node,i)=>{if(node.kind==='identity')positions.set(node.id,{x:500,y:55+identities.indexOf(node)*55,w:270,h:42});else if(node.kind==='container'){const ys={task:180,queue:60,backup:160,completed:260,unlisted:360};positions.set(node.id,{x:node.role==='task'?120:900,y:ys[node.role],w:200,h:52});}else{const n=rules.indexOf(node);positions.set(node.id,{x:190+(n%3)*360,y:h+35+Math.floor(n/3)*70,w:300,h:45});}});
 const marker='structure-arrow-'+graph.selection.side;let out=`<svg class="structure-svg" viewBox="0 0 1120 ${height}" role="img" aria-label="${graph.selection.side} source-linked queue system structure"><defs><marker id="${marker}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10" fill="#728d89"/></marker></defs><text x="20" y="20" fill="#52716d" font-size="13">Arrow labels name relationships; positions are diagram layout, not physical distances.</text>`;
 graph.edges.forEach((edge,index)=>{
  const a=positions.get(edge.from),b=positions.get(edge.to);if(!a||!b)return;
  const rule=edge.kind==='constrains',direction=b.x>a.x?1:-1,x1=a.x+direction*a.w/2,x2=b.x-direction*b.w/2,y1=a.y,y2=b.y;
  const d=rule?`M${a.x} ${a.y-a.h/2} Q${a.x} ${h-18} ${b.x} ${b.y+b.h/2}`:`M${x1} ${y1} C${(x1+x2)/2} ${y1},${(x1+x2)/2} ${y2},${x2} ${y2}`;
  const label=edge.kind==='ready_fifo'?'#'+edge.fifo_rank:edge.kind==='required'?'required':edge.kind==='backup_copy'?'backup':edge.kind==='no_listed_copy'?'no listed copy':edge.label;
  const labelX=edge.kind==='required'?a.x-a.w/2-68:a.x+a.w/2+({ready_fifo:12,backup_copy:52,completed:85,no_listed_copy:12}[edge.kind]||12),labelY=a.y+({required:-8,ready_fifo:-10,backup_copy:8,completed:23,no_listed_copy:10}[edge.kind]||0);
  out+=`<g data-edge="${index}" tabindex="0" role="button" aria-label="Inspect ${esc(edge.label)} for ${esc(edge.from.split('identity:')[1]||'rule')}"><path d="${d}" fill="none" stroke="transparent" stroke-width="14"/><path d="${d}" fill="none" stroke="${colors[edge.kind]||'#718987'}" stroke-width="${rule?1:1.7}" opacity="${rule?.35:.7}" ${rule||edge.kind==='no_listed_copy'?'stroke-dasharray="5 4"':''} marker-end="url(#${marker})"/>${!rule?`<text x="${labelX}" y="${labelY}" fill="${colors[edge.kind]}" font-size="12">${esc(label)}</text>`:''}<title>${esc(edge.label+' · '+edge.status)}</title></g>`;
 });
 graph.nodes.forEach((node,index)=>{
  const p=positions.get(node.id),identity=node.kind==='identity',selected=identity&&selectedIdentity?.side===graph.selection.side&&selectedIdentity?.caseId===graph.selection.case_id&&selectedIdentity?.identity===node.identity;
  const subtitle=identity?[node.detail.required_disposition.replaceAll('_',' '),node.detail.pending_fifo_rank?'FIFO '+node.detail.pending_fifo_rank:null,node.detail.backup_copy?'backup copy retained':null].filter(Boolean).join(' · '):node.kind==='rule'?node.status.replaceAll('_',' '):node.status==='recorded_simulated_container'?'retained simulated state':node.status==='derived_record_condition'?'derived from listed copies':'source task assertion';
  out+=`<g data-node="${index}" tabindex="0" role="button" aria-label="Inspect ${esc(node.label)}"><rect x="${p.x-p.w/2}" y="${p.y-p.h/2}" width="${p.w}" height="${p.h}" rx="8" fill="${selected?'#fff0b9':identity?'#eaf6f2':node.kind==='rule'?'#f0f2ee':'#e8efed'}" stroke="${selected?'#98631f':identity?'#378981':'#a7bbb5'}" stroke-width="${selected?3:1.4}"/><text x="${p.x}" y="${p.y-3}" text-anchor="middle" fill="#183e43" font-size="${identity?16:14}" font-weight="600">${esc(node.label)}</text><text x="${p.x}" y="${p.y+14}" text-anchor="middle" fill="#4e6969" font-size="10.7">${esc(subtitle)}</text><title>${esc(JSON.stringify(node.detail||node.value||node.status))}</title></g>`;
 });
 out+=`<text x="25" y="${h-4}" font-size="13" fill="#647d76">Declared task/model/action constraints · dashed links indicate supplied rules, not newly inferred laws.</text></svg>`;
 return out;
}
function renderSystem(panel,{A,B=null,store,effective=null,onInspect=null,selectedIdentity=null}={}){
 const graphs=[S.graph(A,{store,side:'A'}),...(B?[S.graph(B,{store,side:'B'})]:[])];
 panel.innerHTML=css+`<div class="structure-view"><h2>System map · identities and relations</h2><p class="structure-note">Inspect an identity, relationship, or constraint to open its exact record and source links. Solid memberships describe the selected simulated state. The diagram retains backup copies even when the same job is ready or completed.</p><div class="structure-legend"><span style="--line:#097f91">Ready FIFO membership / rank</span><span style="--line:#985ab4">Listed backup copy</span><span style="--line:#3b865b">Completed</span><span style="--line:#b35d3e">Derived absence from listed copies</span></div>${graphs.map((g,i)=>`<section class="structure-card" data-graph="${i}"><h3>${g.selection.side} · ${esc(g.selection.case_id)} · ${esc(g.selection.scenario_id)} · event ${g.selection.event_index} · ${g.selection.native_time_s} native s</h3><p class="structure-note">World ${esc(g.selection.world_id)} · ${esc(g.native_values.event_kind.replaceAll('_',' '))} · configured rate ${g.native_values.configured_rate} jobs/tick · original deadline ${g.native_values.original_deadline_s} s. Zero new hypotheses inferred.</p><div class="structure-scroll">${systemSvg(g,selectedIdentity)}</div>${g.supplied_claims.map(c=>`<details class="structure-claim"><summary>Source-supplied transfer claim · unverified · not used to build these memberships</summary><p>${esc(c.value)}</p><code>${esc(c.source_refs[0].pointer)}</code></details>`).join('')}<pre class="structure-detail" hidden></pre></section>`).join('')}<p class="structure-note">Identity scope is the native case plus payload ID. A and B stay separate even for the same case and identity; this map never merges alternative worlds.</p></div>`;
 panel.querySelectorAll('[data-graph]').forEach(el=>wire(el,graphs[+el.dataset.graph],onInspect));return {version,graphs};
}
function lineageSvg(graph){
 const positions=new Map(),cal=graph.kind==='calibration_lineage';
 if(cal)graph.nodes.forEach((n,i)=>positions.set(n.id,{x:150+(i%3)*350,y:75+Math.floor(i/3)*180,w:260,h:85}));
 else{const map={source:[140,65],producer:[450,65],record:[780,65],channel:[140,245],frame:[450,245],direct:[780,245],partition:[140,425],encoding:[450,425],render:[780,425]};graph.nodes.forEach(n=>positions.set(n.id,{x:map[n.id][0],y:map[n.id][1],w:250,h:86}));}
 let out=`<svg class="structure-svg" viewBox="0 0 990 ${cal?370:505}" role="img" aria-label="${cal?'Calibration':'Queue'} source-to-view transformation lineage"><defs><marker id="lineage-${cal?'cal':graph.selection.side}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10" fill="#648783"/></marker></defs>`;
 graph.edges.forEach((edge,index)=>{const a=positions.get(edge.from),b=positions.get(edge.to),sameRow=a.y===b.y,x1=sameRow?a.x+a.w/2:a.x,y1=sameRow?a.y:a.y+a.h/2,x2=sameRow?b.x-b.w/2:b.x,y2=sameRow?b.y:b.y-b.h/2,d=sameRow?`M${x1} ${y1}L${x2} ${y2}`:`M${x1} ${y1}C${x1} ${(y1+y2)/2},${x2} ${(y1+y2)/2},${x2} ${y2}`,blocked=edge.status==='selected_record_excluded';out+=`<g data-edge="${index}" tabindex="0" role="button" aria-label="Inspect ${esc(edge.label)}"><path d="${d}" fill="none" stroke="transparent" stroke-width="16"/><path d="${d}" fill="none" stroke="${blocked?'#b96844':'#769890'}" stroke-width="1.8" ${blocked?'stroke-dasharray="5 4"':''} marker-end="url(#lineage-${cal?'cal':graph.selection.side})"/><title>${esc(edge.label+' · '+edge.status)}</title></g>`;});
 graph.nodes.forEach((node,index)=>{const p=positions.get(node.id),status=node.detail?.selected_record_status||node.kind;out+=`<g data-node="${index}" tabindex="0" role="button" aria-label="Inspect ${esc(node.label)}"><rect x="${p.x-p.w/2}" y="${p.y-p.h/2}" width="${p.w}" height="${p.h}" rx="10" fill="${node.kind==='source'?'#e8efee':node.kind==='rendering'||node.kind==='encoding'?'#f4efdf':'#e9f4ed'}" stroke="#91b0a4"/><text x="${p.x}" y="${p.y-12}" text-anchor="middle" font-size="14.5" font-weight="600" fill="#204448">${esc(node.label)}</text><text x="${p.x}" y="${p.y+9}" text-anchor="middle" font-size="11.5" fill="#55716e">${esc(status.replaceAll('_',' '))}</text><text x="${p.x}" y="${p.y+28}" text-anchor="middle" font-size="11" fill="#55716e">Inspect parameters, versions, inputs and loss</text></g>`;});
 return out+'</svg>';
}
function renderLineage(panel,{A,B=null,store,effective=null,channelKey='ready',coefficient=null,onInspect=null}={}){
 const graphs=coefficient?[S.calibrationLineage(coefficient)]:[S.lineage(A,{store,effective,side:'A',channelKey}),...(B?[S.lineage(B,{store,effective,side:'B',channelKey})]:[])];
 panel.innerHTML=css+`<div class="structure-view"><h2>Lineage / transform map</h2><p class="structure-note">Each node opens its actual inputs, parameters, units, versions and omitted information. Connections document computation and source custody; they do not prove causal or empirical truth.</p>${graphs.map((g,i)=>`<section class="structure-card" data-graph="${i}"><h3>${g.kind==='calibration_lineage'?'Separate synthetic calibration':g.selection.side+' · '+esc(g.selection.case_id)+' · event '+g.selection.event_index+' · '+g.selection.native_time_s+' native s'}</h3><p class="structure-note">${esc(g.distinction||g.separation)}</p><div class="structure-scroll">${lineageSvg(g)}</div><div class="lineage-tags">${g.edges.map(e=>`<span>${esc(e.label)}${e.status==='selected_record_excluded'?' · selected event excluded from window':''}</span>`).join('')}</div><pre class="structure-detail" hidden></pre></section>`).join('')}</div>`;
 panel.querySelectorAll('[data-graph]').forEach(el=>wire(el,graphs[+el.dataset.graph],onInspect));return {version,graphs};
}
return Object.freeze({version,renderSystem,renderLineage,systemSvg,lineageSvg,inspectionPayload});
});
