/* Linked views of one existing calibration transform; no queue data enter here. */
(function(root,factory){const node=typeof module==='object'&&module.exports,api=factory(node?require('./timescale.js'):root.CanonTimescale,node?require('./timescale-landscape.js'):root.TimescaleLandscape);if(node)module.exports=api;if(root)root.TimescaleUI=api;})(typeof globalThis!=='undefined'?globalThis:this,function(T,L){
  'use strict';
  const version='timescale-multiview/1',cache=new Map(),panels=new WeakMap();let lastRecipe=null,analysisRuns=0;
  const fmt=x=>Number(x).toFixed(3).replace(/0+$/,'').replace(/\.$/,'');
  const precise=x=>{const parts=Number(x).toPrecision(9).split('e'),mantissa=parts[0].includes('.')?parts[0].replace(/0+$/,'').replace(/\.$/,''):parts[0];return parts.length===2?mantissa+'e'+parts[1]:mantissa;};
  const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone=x=>JSON.parse(JSON.stringify(x));
  function check(ok,message){if(!ok)throw Error(message);}
  // Presentation dimensions are CSS pixels, never analysis inputs or value bounds.
  function layoutDimensions(width,height){
    check(Number.isFinite(width)&&width>0&&Number.isFinite(height)&&height>0,'Plot dimensions must be positive CSS pixels.');
    const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
    return {width,height,stacked:width<760,mapHeight:Math.round(clamp(height*.42,260,760)),rawHeight:Math.round(clamp(height*.22,180,400)),sectionHeight:Math.round(clamp(height*.22,180,400)),kernelHeight:Math.round(clamp(height*.25,200,450)),labelSize:12};
  }
  function sizePlots(state){
    const bounds=state.panel.getBoundingClientRect(),outer=state.panel.closest('.resizable-panel')||state.panel,width=bounds.width,height=outer.getBoundingClientRect().height;
    if(width<=0||height<=0)return false;
    const sizes=layoutDimensions(width,height),key=JSON.stringify(sizes);if(state.layoutKey===key)return false;
    state.layoutKey=key;state.layout=sizes;state.panel.classList.toggle('ts-stacked',sizes.stacked);
    for(const id of ['calMap','calLandscape'])state.$(id).style.height=sizes.mapHeight+'px';
    state.$('calRaw').style.height=sizes.rawHeight+'px';for(const id of ['calTimeSection','calFrequencySection'])state.$(id).style.height=sizes.sectionHeight+'px';state.$('calKernel').style.height=sizes.kernelHeight+'px';
    return true;
  }
  function svgBox(svg){
    const b=svg.getBoundingClientRect(),width=Math.max(300,b.width||600),height=Math.max(160,b.height||200);
    svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.dataset.geometry=JSON.stringify({width,height,label_size_css_px:12});return {width,height,L:64,R:width-30,T:32,B:height-44};
  }
  function resolve(recipe){
    check(recipe&&['chirp','sinusoid','constant'].includes(recipe.signal),'Select a supported calibration signal.');
    check(['retrospective','prefix'].includes(recipe.mode),'Unsupported calibration mode.');
    check(Number.isInteger(recipe.endSample)&&recipe.endSample>=63&&recipe.endSample<=1023,'Invalid permitted calibration endpoint.');
    check(recipe.landscapeVersion===undefined||recipe.landscapeVersion===L.version,'Unsupported landscape version.');
    const key=JSON.stringify([T.version,T.implementationVersion,T.sourceRevision,recipe.signal,recipe.mode,recipe.mode==='prefix'?recipe.endSample:1023]);
    if(!cache.has(key)){cache.set(key,T.analyze(T.makeCalibration(recipe.signal),{mode:recipe.mode,asOfIndex:recipe.endSample}));analysisRuns++;if(cache.size>8)cache.delete(cache.keys().next().value);}
    const result=cache.get(key),row=recipe.row??24,sample=recipe.sample??Math.min(512,result.times_s.length-1),camera=L.validateCamera(recipe.landscapeCamera||L.defaultCamera);
    check(Number.isInteger(row)&&row>=0&&row<result.frequencies_hz.length&&Number.isInteger(sample)&&sample>=0&&sample<result.times_s.length,'Selected coefficient is outside the permitted matrix.');
    const kernelOffset=recipe.kernelOffset??0;check(Number.isInteger(kernelOffset)&&Math.abs(kernelOffset)<=T.kernelRadius(row),'Selected kernel offset is outside the original finite support.');
    return {key,result,row,sample,camera,kernelOffset};
  }
  function getSelection(recipe=lastRecipe){
    if(!recipe)return null;const x=resolve(recipe);lastRecipe=clone(recipe);
    return {result:x.result,support:T.coefficientSupport(x.result,x.row,x.sample),kernelInspection:T.inspectKernel(x.result,x.row,x.sample),recipe:clone(recipe),row:x.row,sample:x.sample,kernelOffset:x.kernelOffset,analysisKey:x.key,rendering:L.renderingRecord(x.result,{camera:x.camera,row:x.row,sample:x.sample})};
  }
  function manifest(recipe=lastRecipe){const s=getSelection(recipe);if(!s)return null;return {version,landscape:s.rendering,map:{data:'same result.magnitude matrix as landscape',magnitude_range:[0,s.result.display.magnitude_max],color_function:'TimescaleLandscape.colorForMagnitude',time_axis:'native sample times; cells reach timestamp midpoints, clipped at first/last center',frequency_axis:'log of scale-center frequency; midpoint cells',selection:{row:s.row,sample:s.sample},edge_overlay:'existing edge_affected flag, white alpha .25'},sections:{time:'selected frequency row of the same magnitude matrix',frequency:'selected sample column of the same magnitude matrix',vertical_bounds:[0,s.result.display.magnitude_max],lines:'existing adjacent values joined for display, no new analytical coefficients'},raw_support:'permitted result.values only; exact computational support highlighted',kernel:{inspection_version:T.kernelInspectionVersion,selected_offset_samples:s.kernelOffset,selected_term:s.kernelInspection.terms[s.kernelOffset+s.kernelInspection.kernel.radius_samples],authority:'original conjugated arrays copied and frozen by inspectKernel',padding:'explicit zero extension, never an observed zero'},cache:{analysis_key:s.analysisKey,excluded:['camera','row','sample','kernel term inspection','panel layout']}};}
  function render(panel,recipe,onChange){
    const selected=getSelection(recipe);let state=panels.get(panel);
    if(!state||!panel.querySelector('#calMap')){state=initialize(panel);panels.set(panel,state);}
    state.recipe=recipe;state.onChange=onChange;state.selected=selected;state.camera=resolve(recipe).camera;
    state.termOffset=selected.kernelOffset;
    const $=state.$,r=selected.result;
    $('calSignal').value=recipe.signal;$('calMode').value=recipe.mode;$('calEnd').value=recipe.endSample;$('calEnd').disabled=recipe.mode==='retrospective';$('calSample').max=r.times_s.length-1;$('calSample').value=selected.sample;$('calRow').max=r.frequencies_hz.length-1;$('calRow').value=selected.row;
    $('calTitle').textContent=r.title+' · '+r.sampling.count+' permitted samples at 128 Hz';
    $('calWindow').textContent=recipe.mode==='prefix'?'As of sample '+recipe.endSample+': the transform uses this prefix only.':'Retrospective centered transform: a coefficient may use samples later than its center.';
    $('calMetadata').textContent=JSON.stringify({source:r.source,sampling:r.sampling,interval:r.interval,implementation:r.implementation_version,contract:r.contract_version,wavelet:r.wavelet,normalization:r.normalization,units:r.units,support_policy:r.support_policy,display:r.display,limitations:r.limitations},null,2);
    sizePlots(state);state.scene.render({result:r,row:selected.row,sample:selected.sample,camera:state.camera});paint(state);cameraStatus(state);
  }
  function initialize(panel){
    panel.innerHTML=`<style>
      .ts-head{display:flex;justify-content:space-between;align-items:baseline;gap:12px;flex-wrap:wrap}.ts-head h2{font-size:18px}.ts-tag{font-size:10px;letter-spacing:.7px;text-transform:uppercase;background:#e9eedf;padding:4px 7px;border-radius:4px;color:#536543}.ts-note{font-size:11px;color:#587266;line-height:1.5;margin:7px 0 10px}.ts-controls{display:flex;gap:13px;align-items:end;flex-wrap:wrap;margin:10px 0}.ts-controls label{display:block;font-size:10px;color:#547064;min-width:150px}.ts-controls select,.ts-controls input[type=number]{display:block;margin-top:4px;width:100%}.ts-controls input[type=range]{min-width:190px}.ts-pair{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12px;margin-top:12px}.ts-plot{min-width:0;border:1px solid #d6e2d9;border-radius:9px;background:#fbfdfa;padding:10px}.ts-plot h3{font-size:12px;margin:0 0 7px}.ts-plot canvas{display:block;width:100%;height:330px;touch-action:none}.ts-cameras{display:flex;gap:4px;align-items:center;flex-wrap:wrap;min-height:30px}.ts-cameras button{font-size:10px;padding:4px 7px}.ts-map-title{min-height:30px;font-size:10px;color:#5a7569}.ts-small{font-size:10px;color:#60796b;line-height:1.45}.ts-selection{padding:9px 11px;border:1px solid #ceded4;border-left:3px solid #bc3b67;border-radius:5px;background:#f4f8f1;font-size:11px;line-height:1.6;margin:10px 0}.ts-sections svg{width:100%;height:155px;display:block}.ts-raw{width:100%;height:155px;display:block}.ts-kernel{width:100%;height:170px;display:block}.ts-evidence{font:10px/1.55 Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere;max-height:330px;overflow:auto;background:#edf3ec;border:1px solid #d6e1d4;padding:10px;border-radius:5px}.ts-term{font-size:11px;line-height:1.65;background:#f5f8f1;border-radius:5px;padding:8px;margin:8px 0}.ts-term-control{display:flex;gap:14px;align-items:center}.ts-term-control label{font-size:10px;min-width:220px;flex:1}.ts-term-control button{font-size:10px}.ts-details{font-size:11px;margin-top:10px}.ts-details summary{cursor:pointer;color:#456557}.ts-axis-note{font-size:10px;color:#667d6e;padding-top:5px}.ts-plot-wide{margin-top:12px}.ts-error{font-size:11px;color:#8c332b}.ts-headingline{display:flex;justify-content:space-between;gap:12px;align-items:center}@media(max-width:850px){.ts-pair{grid-template-columns:1fr}.ts-plot canvas{height:310px}.ts-controls label{min-width:130px}.ts-term-control{flex-wrap:wrap}}
      /* Numeric axes use 1 SVG unit per CSS pixel. Container width controls stacking. */
      .ts-pair{grid-template-columns:minmax(0,1fr) minmax(0,1fr)}.ts-stacked .ts-pair{grid-template-columns:1fr}.ts-plot canvas{height:378px;min-width:300px}.ts-plot svg{max-height:none;overflow:hidden;min-width:300px}.ts-plot{overflow-x:auto}.ts-plot h3,.ts-controls label,.ts-small,.ts-note,.ts-selection,.ts-map-title,.ts-term,.ts-term-control label,.ts-axis-note{font-size:12px}.ts-cameras button,.ts-term-control button{font-size:12px}.ts-sections svg,.ts-raw{height:198px}.ts-kernel{height:225px}.ts-plot svg text{font-family:Segoe UI,Arial,sans-serif;fill:#456459}.ts-map-title{min-height:42px}.ts-cameras{min-height:42px}
      </style>
      <div class="ts-head"><h2>Timescale · one transform, linked views</h2><span class="ts-tag">Synthetic calibration</span></div>
      <p class="ts-note">This separate sampled signal supports the declared transform. Queue events and the State body are not inputs; no queue-frequency inference is made.</p>
      <div class="ts-controls"><label>Calibration signal<select id="calSignal"><option value="chirp">Changing frequency · chirp</option><option value="sinusoid">Known 12 Hz sinusoid</option><option value="constant">Constant · control</option></select></label><label>Analysis window<select id="calMode"><option value="retrospective">Retrospective · all samples</option><option value="prefix">As of sample · recomputed prefix</option></select></label><label>Last permitted sample<input id="calEnd" type="number" min="63" max="1023" step="1"></label></div>
      <p id="calTitle" class="ts-small"></p><p id="calWindow" class="ts-small"></p><p id="calError" class="ts-error" role="alert"></p>
      <div class="ts-pair"><section class="ts-plot"><h3>2D magnitude map</h3><div class="ts-map-title">Click to select the same coefficient in every view.</div><canvas id="calMap" role="img" tabindex="0" aria-label="Synthetic calibration magnitude map"></canvas></section><section class="ts-plot"><h3>3D magnitude landscape</h3><div class="ts-cameras"><button id="calHome" aria-label="Landscape home camera">Home</button><button id="calLeft" aria-label="Orbit landscape left">Orbit left</button><button id="calRight" aria-label="Orbit landscape right">Orbit right</button><button id="calTop" aria-label="Landscape top camera">Top</button><button id="calZoomOut" aria-label="Zoom landscape out">−</button><button id="calZoomIn" aria-label="Zoom landscape in">＋</button></div><canvas id="calLandscape" role="img" tabindex="0" aria-label="Manipulable coefficient magnitude landscape"></canvas><p id="calCamera" class="ts-small"></p></section></div>
      <p id="calStrength" class="ts-axis-note"></p><div class="ts-controls"><label>Coefficient center sample<input id="calSample" type="range" min="0" step="1"></label><label>Frequency row<input id="calRow" type="range" min="0" step="1"></label></div><p id="calSupport" class="ts-selection" role="status"></p>
      <section class="ts-plot ts-plot-wide"><h3>Raw samples and selected computational support</h3><svg id="calRaw" class="ts-raw" role="img" aria-label="Permitted raw calibration samples with selected coefficient support"></svg><p class="ts-small">Only permitted samples are shown; adjacent samples are joined for display. Green marks the finite computational support actually read; outside samples are zero padding.</p></section>
      <div class="ts-pair ts-sections"><section class="ts-plot"><h3 id="calTimeTitle"></h3><svg id="calTimeSection" role="img" aria-label="Selected frequency-row magnitude across permitted time"></svg></section><section class="ts-plot"><h3 id="calFrequencyTitle"></h3><svg id="calFrequencySection" role="img" aria-label="Selected sample-column magnitude across logarithmic frequency"></svg></section></div>
      <section class="ts-plot ts-plot-wide"><div class="ts-headingline"><h3>Actual complex analyzing kernel</h3><button id="calKernelDownload">Download kernel evidence</button></div><p class="ts-small">Exact stored conjugated weights: real (teal), imaginary (purple). Pink marks offsets whose source values are zero-padded.</p><p id="calKernelScale" class="ts-small"></p><svg id="calKernel" class="ts-kernel" role="img" aria-label="Original real and imaginary analyzing kernel and permitted support"></svg><div class="ts-term-control"><label>Inspect kernel offset / source sample<input id="calTerm" type="range" step="1"></label><button id="calTermCenter">Center offset</button></div><p id="calTermStatus" class="ts-term"></p><details class="ts-details"><summary>Exact selected term and source binding</summary><pre id="calTermEvidence" class="ts-evidence"></pre></details><p id="calSum" class="ts-small"></p></section>
      <details class="ts-details"><summary>Selected coefficient evidence</summary><pre id="coefficientEvidence" class="ts-evidence"></pre></details><details class="ts-details"><summary>Transform contract and limitations</summary><pre id="calMetadata" class="ts-evidence"></pre></details><details class="ts-details"><summary>Actual rendering transformations</summary><pre id="calRendering" class="ts-evidence"></pre></details>`;
    const state={panel,$:id=>panel.querySelector('#'+id),termOffset:0};const $=state.$,changed=()=>state.onChange();
    const selectCoefficient=(row,sample)=>{state.recipe.row=row;state.recipe.sample=sample;if(Math.abs(state.recipe.kernelOffset??0)>T.kernelRadius(row))state.recipe.kernelOffset=0;changed();};
    $('calSignal').onchange=e=>{state.recipe.signal=e.target.value;changed();};
    $('calMode').onchange=e=>{state.recipe.mode=e.target.value;state.recipe.sample=Math.min(state.recipe.sample??512,state.recipe.mode==='prefix'?state.recipe.endSample:1023);changed();};
    $('calEnd').onchange=e=>{const v=Number(e.target.value);if(!Number.isInteger(v)||v<63||v>1023){$('calError').textContent='Last permitted sample must be an integer from 63 to 1023.';return;}$('calError').textContent='';state.recipe.endSample=v;if(state.recipe.mode==='prefix')state.recipe.sample=Math.min(state.recipe.sample??512,v);changed();};
    $('calSample').oninput=e=>selectCoefficient(state.selected.row,+e.target.value);$('calRow').oninput=e=>selectCoefficient(+e.target.value,state.selected.sample);
    state.scene=new L.Scene($('calLandscape'),{onSelect:selectCoefficient,onCameraChange:camera=>{state.recipe.landscapeCamera=camera;state.recipe.landscapeVersion=L.version;cameraStatus(state);},onCameraCommit:changed});
    $('calHome').onclick=()=>state.scene.home();$('calLeft').onclick=()=>state.scene.setCamera({yaw:state.scene.getCamera().yaw-.2});$('calRight').onclick=()=>state.scene.setCamera({yaw:state.scene.getCamera().yaw+.2});$('calTop').onclick=()=>state.scene.setCamera({yaw:0,pitch:Math.PI/2});
    $('calZoomOut').onclick=()=>state.scene.setCamera({zoom:Math.max(L.cameraLimits.zoom[0],state.scene.getCamera().zoom/1.15)});$('calZoomIn').onclick=()=>state.scene.setCamera({zoom:Math.min(L.cameraLimits.zoom[1],state.scene.getCamera().zoom*1.15)});
    $('calMap').onclick=e=>{const b=e.currentTarget.getBoundingClientRect(),g=state.mapGeometry,r=state.selected.result;if(!g)return;const x=e.clientX-b.left,y=e.clientY-b.top;if(x<g.L||x>g.R||y<g.T||y>g.B)return;const sample=Math.max(0,Math.min(r.times_s.length-1,Math.round((x-g.L)/(g.R-g.L)*(r.times_s.length-1)))),row=Math.max(0,Math.min(r.frequencies_hz.length-1,Math.round((g.B-y)/(g.B-g.T)*(r.frequencies_hz.length-1))));selectCoefficient(row,sample);};
    const keySelect=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const s=state.selected,r=s.result,sample=Math.max(0,Math.min(r.times_s.length-1,s.sample+(e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:0))),row=Math.max(0,Math.min(r.frequencies_hz.length-1,s.row+(e.key==='ArrowDown'?-1:e.key==='ArrowUp'?1:0)));selectCoefficient(row,sample);};$('calMap').onkeydown=keySelect;$('calLandscape').onkeydown=keySelect;
    $('calTerm').oninput=e=>{state.recipe.kernelOffset=+e.target.value;changed();};$('calTermCenter').onclick=()=>{state.recipe.kernelOffset=0;changed();};
    $('calKernelDownload').onclick=()=>{const blob=new Blob([JSON.stringify(state.selected.kernelInspection,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='calibration-kernel-evidence.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);};
    state.observer=typeof ResizeObserver==='function'?new ResizeObserver(()=>{if(state.selected&&sizePlots(state)){paint(state);state.scene.draw();cameraStatus(state);}}):null;
    state.observer?.observe(panel);const outer=panel.closest('.resizable-panel');if(outer&&outer!==panel)state.observer?.observe(outer);return state;
  }
  function cameraStatus(state){const c=state.scene.getCamera();state.$('calCamera').textContent='Orthographic · yaw '+fmt(c.yaw)+' rad · pitch '+fmt(c.pitch)+' rad · zoom '+fmt(c.zoom)+'×. Camera changes presentation only.';if(state.selected)state.$('calRendering').textContent=JSON.stringify({...manifest(state.recipe),landscape:state.scene.manifest()},null,2);}
  function paint(state){
    const $=state.$,s=state.selected,r=s.result,support=s.support;paintMap(state);paintRaw(state);paintSections(state);paintKernel(state);
    const status='Sample '+s.sample+' · '+fmt(r.times_s[s.sample])+' s · row '+s.row+' / '+fmt(r.frequencies_hz[s.row])+' Hz · |W| '+precise(r.magnitude[s.row][s.sample])+'. '+(support.edge_affected?'Inside':'Outside')+' the edge-effect convention. Permitted support '+support.observed_sample_range.join('–')+'; zero padding '+support.padding_samples.left+' left / '+support.padding_samples.right+' right.';
    $('calSupport').textContent=status;$('coefficientEvidence').textContent=JSON.stringify(support,null,2);$('calMap').setAttribute('aria-label','2D calibration magnitude map. '+status);$('calLandscape').setAttribute('aria-label','3D calibration magnitude landscape. '+status+' Drag to orbit; click a coefficient.');
    $('calStrength').textContent='Both views use magnitude bounds 0–'+precise(r.display.magnitude_max)+' '+r.units.coefficient+'. Frequency is logarithmic (4–32 Hz). White edge overlay is a convention, not significance. These bounds belong to this permitted result; do not compare independently ranged color strength across signals.';
  }
  function paintMap(state){
    const c=state.$('calMap'),ctx=c.getContext('2d'),b=c.getBoundingClientRect(),w=Math.max(300,b.width||500),h=Math.max(240,b.height||330),dpr=Math.min(globalThis.devicePixelRatio||1,2);c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);
    const s=state.selected,r=s.result,n=r.times_s.length,m=r.frequencies_hz.length,L0=54,R=w-25,T0=28,B=h-85,W=R-L0,H=B-T0,maximum=r.display.magnitude_max,X=k=>L0+k/(n-1)*W,Y=j=>B-j/(m-1)*H;
    state.mapGeometry={L:L0,R,T:T0,B};ctx.fillStyle='#fcfefb';ctx.fillRect(0,0,w,h);ctx.save();ctx.beginPath();ctx.rect(L0,T0,W,H);ctx.clip();
    for(let j=0;j<m;j++)for(let k=0;k<n;k++){const x0=X(Math.max(0,k-.5)),x1=X(Math.min(n-1,k+.5)),y0=Y(Math.min(m-1,j+.5)),y1=Y(Math.max(0,j-.5));ctx.fillStyle=L.colorForMagnitude(r.magnitude[j][k],maximum);ctx.fillRect(x0,y0,x1-x0+.3,y1-y0+.3);if(r.edge_affected[j][k]){ctx.fillStyle='rgba(255,255,255,.25)';ctx.fillRect(x0,y0,x1-x0+.3,y1-y0+.3);}}
    const x=X(s.sample),y=Y(s.row);ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=.8;ctx.beginPath();ctx.moveTo(x,T0);ctx.lineTo(x,B);ctx.moveTo(L0,y);ctx.lineTo(R,y);ctx.stroke();ctx.strokeStyle='#cf315e';ctx.lineWidth=2;ctx.strokeRect(x-4,y-4,8,8);ctx.restore();
    ctx.font='12px Segoe UI';ctx.fillStyle='#456459';ctx.textAlign='right';for(const f of[4,8,16,32])ctx.fillText(String(f),L0-7,B-Math.log(f/4)/Math.log(8)*H+4);ctx.textAlign='left';ctx.fillText('Hz · log',4,16);ctx.textAlign='right';ctx.fillText('Native time (s)',R,B+36);for(let i=0;i<=4;i++){ctx.textAlign='center';ctx.fillText(fmt(r.times_s[0]+(r.times_s.at(-1)-r.times_s[0])*i/4),L0+W*i/4,B+18);}ctx.textAlign='left';
    const barW=Math.min(200,W-25),gradient=ctx.createLinearGradient(L0,0,L0+barW,0);for(let i=0;i<=10;i++)gradient.addColorStop(i/10,L.colorForMagnitude(maximum*i/10,maximum));ctx.fillStyle=gradient;ctx.fillRect(L0,B+48,barW,10);ctx.fillStyle='#456459';ctx.fillText('0',L0,B+75);ctx.textAlign='right';ctx.fillText(fmt(maximum)+' |W|',L0+barW,B+75);
    c.dataset.selection=JSON.stringify({row:s.row,sample:s.sample,time_s:r.times_s[s.sample],frequency_hz:r.frequencies_hz[s.row],magnitude:r.magnitude[s.row][s.sample]});
  }
  function paintRaw(state){
    const s=state.selected,r=s.result,k=s.kernelInspection,term=k.terms[state.termOffset+k.kernel.radius_samples],svg=state.$('calRaw'),g=svgBox(svg),n=r.values.length,X=i=>g.L+i/(n-1)*(g.R-g.L),Y=v=>(g.T+g.B)/2-v*(g.B-g.T)/2;let path='';for(let i=0;i<n;i++)path+=(i?'L':'M')+X(i)+' '+Y(r.values[i]);
    const first=s.support.observed_sample_range[0],last=s.support.observed_sample_range[1];let html=`<title>Permitted native samples and exact coefficient support</title><rect x="${X(first)}" y="${g.T}" width="${Math.max(1,X(last)-X(first))}" height="${g.B-g.T}" fill="#dfeee0"/><path d="M${g.L} ${Y(0)}H${g.R}" stroke="#b8cdbd"/><text x="${g.L}" y="16" font-size="12">Amplitude (a.u.)</text><path d="${path}" stroke="#167e85" fill="none" stroke-width="1"/><path d="M${X(s.sample)} ${g.T}V${g.B}" stroke="#ba3d68"/>`;
    for(const v of [1,0,-1])html+=`<text x="${g.L-8}" y="${Y(v)+4}" text-anchor="end" font-size="12">${v}</text>`;
    for(let i=0;i<=4;i++)html+=`<text x="${X(i*(n-1)/4)}" y="${g.B+21}" text-anchor="middle" font-size="12">${fmt(r.times_s[0]+(r.times_s.at(-1)-r.times_s[0])*i/4)}</text>`;
    html+=`<text x="${g.R}" y="${g.height-3}" text-anchor="end" font-size="12">Native time (s)</text>`;
    if(term.status==='permitted_sample')html+=`<circle cx="${X(term.source_sample_index)}" cy="${Y(term.source_value)}" r="4" fill="#9b61b6" stroke="white"/>`;
    else html+='<desc>Selected term is zero padding, not an observation. No observed sample marker is drawn.</desc>';
    svg.innerHTML=html;
  }
  function section(svg,xs,ys,selected,maximum,{log=false,xlabel='',title=''}){
    const g=svgBox(svg),L0=g.L,R=g.R,T0=g.T,B=g.B,x0=xs[0],x1=xs.at(-1),X=x=>L0+(log?Math.log(x/x0)/Math.log(x1/x0):(x-x0)/(x1-x0))*(R-L0),Y=y=>B-(maximum>0?y/maximum:0)*(B-T0);let path='';for(let i=0;i<xs.length;i++)path+=(i?'L':'M')+X(xs[i])+' '+Y(ys[i]);
    let html=`<title>${esc(title)}</title><path d="M${L0} ${T0}V${B}H${R}" fill="none" stroke="#bccdc0"/><text x="${L0-7}" y="${T0+4}" text-anchor="end" font-size="12">${fmt(maximum)}</text><text x="${L0-7}" y="${B+4}" text-anchor="end" font-size="12">0</text><text x="${L0}" y="16" font-size="12">Magnitude |W|</text><path d="${path}" fill="none" stroke="#167d86" stroke-width="1.5"/><path d="M${X(xs[selected])} ${T0}V${B}" stroke="#b84870" stroke-dasharray="3 3"/><circle cx="${X(xs[selected])}" cy="${Y(ys[selected])}" r="3.4" fill="#bf3e6e"/><text x="${R}" y="${g.height-3}" text-anchor="end" font-size="12">${esc(xlabel)}</text>`;
    for(let i=0;i<=4;i++){const t=log?x0*Math.pow(x1/x0,i/4):x0+(x1-x0)*i/4;html+=`<text x="${X(t)}" y="${B+21}" text-anchor="middle" font-size="12">${fmt(t)}</text>`;}
    svg.dataset.magnitudeBounds=JSON.stringify([0,maximum]);svg.innerHTML=html;
  }
  function paintSections(state){const s=state.selected,r=s.result,$=state.$;$('calTimeTitle').textContent='Through time · '+fmt(r.frequencies_hz[s.row])+' Hz';$('calFrequencyTitle').textContent='Across frequency · '+fmt(r.times_s[s.sample])+' s';section($('calTimeSection'),r.times_s,r.magnitude[s.row],s.sample,r.display.magnitude_max,{xlabel:'native seconds',title:'Existing selected frequency row of the magnitude matrix'});section($('calFrequencySection'),r.frequencies_hz,r.magnitude.map(row=>row[s.sample]),s.row,r.display.magnitude_max,{log:true,xlabel:'center frequency Hz · log',title:'Existing selected sample column of the magnitude matrix'});}
  function paintKernel(state){
    const s=state.selected,inspection=s.kernelInspection,k=inspection.kernel,terms=inspection.terms,$=state.$,q=state.termOffset+k.radius_samples,term=terms[q];$('calTerm').min=-k.radius_samples;$('calTerm').max=k.radius_samples;$('calTerm').value=state.termOffset;
    const svg=$('calKernel'),g=svgBox(svg),xs=k.offsets_s,x0=xs[0],x1=xs.at(-1),maximum=Math.max(...k.real.map(Math.abs),...k.imag.map(Math.abs)),X=x=>g.L+(x-x0)/(x1-x0)*(g.R-g.L),Y=y=>(g.T+g.B)/2-y/maximum*(g.B-g.T)/2;let re='',im='';for(let i=0;i<xs.length;i++){re+=(i?'L':'M')+X(xs[i])+' '+Y(k.real[i]);im+=(i?'L':'M')+X(xs[i])+' '+Y(k.imag[i]);}
    const first=terms.find(t=>t.status==='permitted_sample').offset_s,last=terms.findLast(t=>t.status==='permitted_sample').offset_s;
    let html=`<title>Original conjugated kernel arrays, not a reconstructed curve</title><rect x="${g.L}" y="${g.T}" width="${Math.max(0,X(first)-g.L)}" height="${g.B-g.T}" fill="#f5e3e9"/><rect x="${X(last)}" y="${g.T}" width="${Math.max(0,g.R-X(last))}" height="${g.B-g.T}" fill="#f5e3e9"/><path d="M${g.L} ${Y(0)}H${g.R}" stroke="#c6d4c7"/><path d="${re}" fill="none" stroke="#167f87" stroke-width="1.4"/><path d="${im}" fill="none" stroke="#9259a6" stroke-width="1.2"/><path d="M${X(term.offset_s)} ${g.T}V${g.B}" stroke="#b33f69"/><circle cx="${X(term.offset_s)}" cy="${Y(term.kernel_real)}" r="3" fill="#147d88"/><circle cx="${X(term.offset_s)}" cy="${Y(term.kernel_imag)}" r="3" fill="#9455a9"/><text x="${g.L}" y="16" font-size="12">Conjugated multiplier</text>`;
    for(const y of [maximum,0,-maximum])html+=`<text x="${g.L-8}" y="${Y(y)+4}" text-anchor="end" font-size="12">${fmt(y)}</text>`;
    for(const x of[x0,0,x1])html+=`<text x="${X(x)}" y="${g.B+21}" text-anchor="middle" font-size="12">${fmt(x)}</text>`;
    html+=`<text x="${g.R}" y="${g.height-3}" text-anchor="end" font-size="12">Offset from center (s)</text>`;svg.innerHTML=html;
    $('calKernelScale').textContent='Scale '+precise(k.scale)+' samples · finite radius '+k.radius_samples+' samples.';
    $('calTermStatus').textContent='Offset '+term.offset_samples+' samples ('+fmt(term.offset_s)+' s) → '+(term.status==='permitted_sample'?'native sample '+term.source_sample_index+' at '+fmt(term.source_time_s)+' s, x = '+precise(term.source_value):'explicit zero padding at requested index '+term.source_sample_index)+'. Kernel = '+precise(term.kernel_real)+' + i('+precise(term.kernel_imag)+'). Contribution = '+precise(term.contribution_real)+' + i('+precise(term.contribution_imag)+').';
    $('calTermEvidence').textContent=JSON.stringify({source:inspection.source,term,source_value_origin:term.status==='permitted_sample'?'result.values['+term.source_sample_index+'] at result.times_s['+term.source_sample_index+']':'none; zero extension outside the permitted result',kernel_array_origin:'private stored kernels['+s.row+'] copied by inspectKernel; index '+term.kernel_index,coefficient_binding:{scale_index:s.row,sample_index:s.sample},implementation_version:inspection.kernel.implementation_version},null,2);
    $('calSum').textContent='Complex contribution sum: '+precise(inspection.reconstructed.real)+' + i('+precise(inspection.reconstructed.imag)+'). '+(inspection.reconstructed.exactly_matches_complex_coefficient?'Exactly matches the stored coefficient.':'Mismatch: inspect evidence before interpretation.')+' Padding contributes zero. Kernel and support are not probability distributions.';
  }
  return Object.freeze({version,render,getSelection,manifest,layoutDimensions,formatNumber:precise,cacheStats:()=>({analysisRuns,entries:cache.size,keys:[...cache.keys()]})});
});
