/* Local interaction instrument. Model/evidence, display transforms and playback stay separate. */
(()=>{'use strict';
const $=id=>document.getElementById(id),M=ObservatoryModel,F=ObservatoryForm,D=JSON.parse($('observatoryData').textContent);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=x=>JSON.parse(JSON.stringify(x)),pretty=x=>JSON.stringify(x,null,2),number=x=>{if(x==null)return 'missing';const a=Number(x).toPrecision(6).split('e');if(a[0].includes('.'))a[0]=a[0].replace(/0+$/,'').replace(/\.$/,'');return a.join('e');};
let S=M.defaultState(),lastTick=performance.now(),lastDraw=0,lastMetric=0,metric=null,metricKey='',signalDrag=null,formTime=0;
const music=decodePCM(D.music.wavBase64);music.sha256=D.sources.music.sha256;
const scene=new F.Scene($('formCanvas'),{onCameraChange:c=>{S.camera=c;cameraStatus();},onPick:p=>{S.transport.playing=false;stopAudio();S.transport.time=formTime;S.inspection.contribution={side:p.side,key:p.key};setTask('inspect');}});
let audioContext=null,audioNode=null,audioBuffer=null,audioKey='',audioGeneration=0,audioOrigin=null;
function decodePCM(base64){const binary=atob(base64),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0)),v=new DataView(bytes.buffer);let p=12,rate=0,channels=0,bits=0,start=0,length=0;while(p+8<=bytes.length){const id=String.fromCharCode(...bytes.slice(p,p+4)),size=v.getUint32(p+4,true);if(id==='fmt '){if(v.getUint16(p+8,true)!==1)throw Error('Only retained PCM is supported');channels=v.getUint16(p+10,true);rate=v.getUint32(p+12,true);bits=v.getUint16(p+22,true);}if(id==='data'){start=p+8;length=size;}p+=8+size+(size%2);}if(channels!==2||bits!==16||rate!==22050||start+length>bytes.length)throw Error('Retained stereo sample contract mismatch');const n=length/4,left=new Float32Array(n),right=new Float32Array(n);for(let i=0;i<n;i++){left[i]=v.getInt16(start+i*4,true)/32768;right[i]=v.getInt16(start+i*4+2,true)/32768;}return {sampleRate:rate,left,right,duration:n/rate};}
function calibration(state=S){return state.source==='music'?[{key:'left',label:'Left RMS · trailing 50 ms',unit:'PCM amplitude',scale:.16},{key:'right',label:'Right RMS · trailing 50 ms',unit:'PCM amplitude',scale:.16}]:[{key:'position',label:'Position',unit:'synthetic u',scale:1},{key:'velocity',label:'Velocity',unit:'synthetic u/s',scale:Math.PI}];}
function windowFor(state=S){const t=state.transport,end=Math.min(t.end,Math.max(t.time,t.start+t.span));return {start:Math.max(t.start,end-t.span),end};}
function sample(side,time,state=S){return M.sample(state,side,time,music);}
function historyFrames(state=S){
 const policy='2 retained B frames; no time averaging',frames=[],omitted=[];
 if(state.source!=='oscillator')return {policy,status:'unsupported',reason:'This bounded history view supports generated oscillator frames only.',frames,omitted};
 if(state.transport.persistence===0)return {policy,status:'disabled',reason:'Trace persistence is zero.',frames,omitted};
 const requestedDisplayTimes=[state.transport.time-state.transport.persistence,state.transport.time-state.transport.persistence/2];
 for(const displayTime of requestedDisplayTimes){
  if(displayTime<0){omitted.push({displayTime,reason:'Before the supported display history begins.'});continue;}
  const nativeSample=sample('B',displayTime,state);
  if(nativeSample.valid)frames.push({displayTime,sample:nativeSample});else omitted.push({displayTime,reason:nativeSample.reason,sample:nativeSample});
 }
 return {policy,status:frames.length?'available':'unavailable',origin:'Evaluations of the declared generated oscillator recipe; not empirical temporal observations.',requestedDisplayTimes,frames,omitted};
}
function inspectionContribution(state=S){
 const selected=state.inspection.contribution;if(!selected)return null;
 const frame=formSample(selected.side,state.transport.time,state),base={side:selected.side,key:selected.key,displayTime:state.transport.time,nativeTime:frame.nativeTime,source:D.sources[state.source],sourceRefs:frame.sourceRefs,derivation:frame.derived};
 if(!frame.valid)return {...base,status:'unavailable',reason:frame.reason};
 const contribution=F.normalizeChannels(frame.channels,calibration(state)).find(item=>item.key===selected.key);
 return {...base,status:'recomputed_from_current_selection',encoding:state.encoding,...contribution};
}
function formSample(side,time,state=S){const x=sample(side,time,state);if(state.source!=='music'||!x.valid)return x;const c={left:0,right:0},shift=side==='B'?state.align.shift:0,nativeTime=time-shift,end=Math.min(music.left.length,Math.floor(nativeTime*music.sampleRate)+1),start=Math.max(0,end-Math.round(.05*music.sampleRate));for(const key of ['left','right']){for(let i=start;i<end;i++){const v=side==='B'?music[key][i]*state.align.gain+state.align.offset:music[key][i];c[key]+=v*v;}c[key]=Math.sqrt(c[key]/Math.max(1,end-start));}return {...x,channels:c,derived:{...x.derived,bodyFrame:'RMS of transformed PCM over trailing permitted 50 ms, not an instantaneous raw amplitude',sampleRange:[start,end-1],frameSeconds:.05}};}
function renderingRecord(state){return {version:'observatory-rendering/1',form:state.source==='lake'?{kind:'native catalogue relationships',temporal_geometry:'not available'}:F.describe({encoding:state.encoding,camera:state.camera,calibration:calibration(state)}),selected:state.source==='lake'?{identity:state.selectedLakeId}: {a:formSample('A',state.transport.time,state),b:formSample('B',state.transport.time,state)},history:historyFrames(state),inspection:{selection:state.inspection.contribution,selectedContribution:inspectionContribution(state),openDetails:state.inspection.openDetails},signal:{window:windowFor(state),calibration:state.source==='music'?{left:[-1,1],right:[-1,1]}:{position:[-2.5,2.5],velocity:[-10,10]},rendering:'CSS-pixel plot; synthetic equations sampled for display; music uses native PCM min/max bins per pixel; no invented intermediate PCM samples',selection:'One shared display time; candidate native time = display time − shift'},audio:{source:state.source==='music'?'retained stereo PCM after declared candidate alignment':state.source==='oscillator'?'explicit sonification: pitchHz=clamp(220+110*position,40,880), continuous phase integration, amplitude .12':'unavailable',playback:'same display cursor/speed/loop; 20 Hz highpass removes DC; master gain .35; mix both averages A and B; clipping to [-1,1] at playback only',state:state.audio},capture:'No viewport or historical pixel captures are asserted as replay-validated facts.'};}
function setTask(task){S.task=task;S.panel.inspect=task==='inspect';syncControls();paint(true);}
function isTune(){return S.task==='tune';}
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function syncControls(){
 ensureExactInputs();
 syncInspectionDetails();
 const lake=S.source==='lake',musicSource=S.source==='music';
 document.querySelectorAll('[data-task]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.task===S.task||(b.dataset.task==='compare'&&['align','tune'].includes(S.task))));
 $('choosePanel').hidden=S.task!=='choose';$('comparePanel').hidden=['choose','inspect'].includes(S.task);$('inspectPanel').hidden=S.task!=='inspect';$('alignPanel').hidden=lake||isTune();$('tunePanel').hidden=lake||!isTune()||S.source!=='oscillator';$('unsupportedTune').hidden=!lake&&(!isTune()||S.source==='oscillator');$('unsupportedTune').textContent=lake?'Catalogue metadata has no supported numeric time comparison. Choose a sampled source or Inspect recorded relationships.':'Model tuning applies only to the generated oscillator. Retained audio and lake records do not expose a simulated dynamics model.';$('alignTab').disabled=lake;$('tuneTab').disabled=lake;$('alignTab').setAttribute('aria-pressed',!lake&&!isTune());$('tuneTab').setAttribute('aria-pressed',!lake&&isTune());
 $('referenceName').textContent=lake?'World Bank entity catalogue':musicSource?'Eight bars · retained stereo':'Oscillator · 0.500 Hz · locked';$('referenceDetail').textContent=lake?'Static records · no sampled time signal':musicSource?'Original composed example · 16 s / 120 BPM':'Position + velocity · native support 0–16 s';
 const options=lake?[['current','Selected native entity']]:musicSource?[['current','Same stereo source · Align B']]:[['current',(S.alternatives.find(a=>M.stable(a.tune)===M.stable(S.tune))?.name||'Current generated candidate')],...S.alternatives.map((a,i)=>[String(i),a.name])];$('candidateSelect').innerHTML=options.map(([v,label])=>'<option value="'+v+'">'+esc(label)+'</option>').join('');$('candidateSelect').disabled=lake||musicSource;
 $('dynamicStage').hidden=lake;$('lakeStage').hidden=!lake;$('transport').hidden=lake;$('signalPanel').hidden=lake;$('encoding').disabled=lake;$('homeCamera').disabled=lake;$('formTitle').textContent=lake?'Recorded entities and relationships':'One evolving form';$('formSubtitle').textContent=lake?'Native values retained · coverage and missingness inspectable':'Shared coordinates and value scales · A amber / B cyan';
 $('scrub').min=S.transport.start;$('scrub').max=S.transport.end;const bounds=$('scrub').parentElement.querySelectorAll('span');bounds[0].textContent=S.transport.start+' s';bounds[1].textContent=S.transport.end+' s';$('encoding').value=S.encoding;$('play').textContent=S.transport.playing?'Pause':'Play';$('listen').textContent=S.audio.enabled?'Mute':'Listen';$('audioMix').value=S.audio.mix;$('loop').checked=S.transport.loop;for(const k of ['speed','span','persistence'])setSelect($(k),S.transport[k]);
 for(const k of ['shift','gain','offset']){setRange($(k),S.align[k]);$(k+'Exact').value=String(S.align[k]);$(k+'Exact').disabled=lake;$(k+'Value').textContent=Number(S.align[k]).toFixed(k==='shift'?3:2)+(k==='shift'?' s':'');$(k).disabled=lake;}
 for(const k of ['frequency','amplitude','phase','damping']){setRange($(k),S.tune[k]);$(k+'Exact').value=String(S.tune[k]);$(k+'Exact').disabled=S.source!=='oscillator';$(k+'Value').textContent=Number(S.tune[k]).toFixed(3)+({frequency:' Hz',amplitude:' u',phase:' rad',damping:' /s'}[k]);}
 $('alignExplanation').textContent=musicSource?'Both PCM channels: yB(t) = gain × nativeB(t − shift) + offset. Out-of-support samples remain missing.':'Position: gain × xB(t − shift) + offset. Velocity: gain × vB(t − shift). Offset does not change the derivative.';
 $('sourceType').textContent=musicSource?'Retained PCM · body shows 50 ms channel RMS':'Generated analytic oscillator pair';$('signalTitle').textContent=musicSource?'Stereo waveform · left and right':'Position + velocity';$('signalHint').textContent=musicSource?'Native PCM min/max bins · click to scrub':'Click to scrub · Shift-drag to align B';$('trajectory').hidden=!musicSource;
 $('signalPanel').style.height=(S.panel.height+85+(musicSource?35:0))+'px';
 if(musicSource){$('trajectory').innerHTML=D.music.metadata.bars.map(b=>'<button data-bar="'+b.start_s+'" class="'+(S.transport.time>=b.start_s&&S.transport.time<b.end_s?'current':'')+'" aria-label="Go to supplied bar '+b.index+'">'+(b.index===1?'A · ':b.index===5?'A′ · ':'')+'Bar '+b.index+'</button>').join('');$('trajectory').querySelectorAll('[data-bar]').forEach(b=>b.onclick=()=>seek(+b.dataset.bar));}
 if(lake){$('windowNote').textContent='Recorded catalogue relationships remain available through Inspect.';renderLake();}cameraStatus();
}
function syncInspectionDetails(){
 const ids={native:'nativeDetails',source:'sourceDetails',receipt:'receiptDetails',lakes:'lakeDetails'};
 for(const [key,id]of Object.entries(ids)){
  const detail=$(id).parentElement,open=S.inspection.openDetails.includes(key);if(detail.open!==open)detail.open=open;
  detail.ontoggle=()=>{S.inspection.openDetails=Object.entries(ids).filter(([,preId])=>$(preId).parentElement.open).map(([name])=>name);if(S.task==='inspect')inspect();};
 }
}
function setSelect(el,value){if(![...el.options].some(o=>+o.value===value)){const o=document.createElement('option');o.value=value;o.textContent=value+' (saved)';el.appendChild(o);}el.value=value;}
function setRange(el,value){el.min=Math.min(+el.min,value);el.max=Math.max(+el.max,value);const step=Number(el.step),q=(value-Number(el.min))/step;if(el.step!=='any'&&step>0&&Math.abs(q-Math.round(q))>1e-9)el.step='any';el.value=value;}
function ensureExactInputs(){
 const labels={shift:'time shift',gain:'gain',offset:'offset',frequency:'model frequency',amplitude:'model amplitude',phase:'model phase',damping:'model damping'};
 for(const [key,label]of Object.entries(labels)){
  if($(key+'Exact'))continue;const el=document.createElement('input'),group=['shift','gain','offset'].includes(key)?'align':'tune';
  el.id=key+'Exact';el.type='number';el.step='any';el.min=M.limits[key][0];el.max=M.limits[key][1];el.style.width='100px';el.style.flexShrink='0';el.title='Press Enter or leave the field to apply';el.setAttribute('aria-label','Exact candidate '+label);
  const commit=()=>{try{if(el.value.trim()==='')throw Error('Enter a finite exact value.');const value=Number(el.value);if(value===S[group][key])return;const next=clone(S);next[group][key]=value;M.validateState(next);S=next;change();status('Exact candidate '+label+' set to '+value+'.');}catch(error){el.value=String(S[group][key]);status(error.message,true);}};
  el.onchange=commit;el.onblur=commit;el.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();commit();}};
  $(key).closest('label').querySelector('.row').appendChild(el);
 }
}
function cameraStatus(){$('cameraStatus').textContent='Orbit '+S.camera.yaw.toFixed(2)+' · depth '+S.camera.pitch.toFixed(2)+' · '+S.camera.zoom.toFixed(2)+'×';}
function valuesHtml(label,x,side){return '<span class="badge '+(side==='B'?'b':'')+'">'+label+'</span><br>'+(x.valid?Object.entries(x.channels).map(([k,v])=>esc(k)+' <strong>'+number(v)+'</strong>').join(' · '):'Outside native source support — missing')+'<div class="small">'+(x.valid?'native t '+number(x.nativeTime)+' s':'No zero substitution')+'</div>';}
function paint(force=false){
 if(S.source==='lake'){if(S.task==='inspect')inspect();return;}
 const t=S.transport.time,a=formSample('A',t),b=formSample('B',t);$('clock').textContent=t.toFixed(3)+' s';$('scrub').value=t;
 $('formCanvas').style.visibility=a.valid?'visible':'hidden';$('depthNote').textContent=a.valid?'Drag to orbit · Shift-drag to pan · wheel to zoom':'Outside native support · no geometry substituted';formTime=t;if(a.valid){const trail=historyFrames(S).frames.map(frame=>({channels:frame.sample.channels,label:'B at '+frame.displayTime.toFixed(3)+' s'}));scene.render({a:{channels:a.channels,label:'Reference A'},b:b.valid?{channels:b.channels,label:'Candidate B'}:null,calibration:calibration(),encoding:S.encoding,camera:S.camera,trail});}
 $('valuesA').innerHTML=valuesHtml('A · REFERENCE',a,'A');$('valuesB').innerHTML=valuesHtml('B · CANDIDATE',b,'B');cameraStatus();
 paintSignal();const now=performance.now(),w=windowFor(),key=JSON.stringify([S.source,S.tune,S.align,w]);if(force||now-lastMetric>650){if(key!==metricKey){metric=M.metrics(S,w,music);metricKey=key;}$('metrics').innerHTML=Object.entries(metric.channels||{}).map(([k,v])=>'<span>'+esc(k)+' RMSE <strong>'+number(v.rmse)+'</strong><br>max |Δ| '+number(v.maxAbsoluteError)+'</span>').join('')+'<span>Paired coverage <strong>'+((metric.coverage?.fraction||0)*100).toFixed(1)+'%</strong><br>window ['+w.start.toFixed(2)+', '+w.end.toFixed(2)+') s</span>';$('windowNote').textContent='Remaining differences use named channels over ['+w.start.toFixed(2)+', '+w.end.toFixed(2)+') display seconds. Missing pairs reduce coverage; matching here does not establish whole-state equivalence.';lastMetric=now;}
 if(S.source==='music')$('trajectory').querySelectorAll('[data-bar]').forEach(b=>b.classList.toggle('current',t>=+b.dataset.bar&&t<+b.dataset.bar+2));
 if(S.task==='inspect'&&(force||now-lastInspect>500)){inspect();lastInspect=now;}
 $('audioStatus').textContent=S.audio.enabled?(audioContext?.state==='running'&&audioNode?'Audio running · '+S.audio.mix:'Audio armed · press Play'):'Audio off';$('audioStatus').dataset.contextState=audioContext?.state||'not-created';
}
let lastInspect=0,signalPlotCache=null,signalPlotBuilds=0;
function paintSignal(){
 const canvas=$('signalCanvas'),r=canvas.getBoundingClientRect(),w=Math.max(330,r.width),h=Math.max(150,r.height),dpr=Math.min(devicePixelRatio||1,2),pixelWidth=Math.round(w*dpr),pixelHeight=Math.round(h*dpr);
 if(canvas.width!==pixelWidth)canvas.width=pixelWidth;if(canvas.height!==pixelHeight)canvas.height=pixelHeight;
 const win=windowFor(),L=64,R=w-20,keys=S.source==='music'?['left','right']:['position','velocity'],ranges=S.source==='music'?[1,1]:[2.5,10],X=t=>L+(t-win.start)/(win.end-win.start)*(R-L);
 // Cache only the presentation of an identical observation window. Cursor,
 // camera, playback speed and audition do not change any plotted values.
 const key=JSON.stringify([M.version,D.sources[S.source],S.source,S.tune,S.align,win,w,h,dpr,keys,ranges]),rebuild=signalPlotCache?.key!==key;
 if(rebuild){
  const layer=signalPlotCache?.canvas||document.createElement('canvas');layer.width=pixelWidth;layer.height=pixelHeight;
  const c=layer.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle='#111f29';c.fillRect(0,0,w,h);c.font='12px Segoe UI';let clipped=false;
  for(let j=0;j<2;j++){const top=22+j*(h-30)/2,bot=top+(h-30)/2-25,mid=(top+bot)/2,range=ranges[j],Y=v=>mid-v/range*(bot-top)/2;c.strokeStyle='#31424d';c.beginPath();c.moveTo(L,top);c.lineTo(L,bot);c.moveTo(L,mid);c.lineTo(R,mid);c.stroke();c.fillStyle='#a8c2c5';c.fillText(keys[j],3,top+13);c.fillText('±'+range,3,top+28);c.save();c.beginPath();c.rect(L,top,R-L,bot-top);c.clip();
   for(const side of ['A','B']){c.strokeStyle=side==='A'?'#eabb76':'#63d9d1';c.lineWidth=side==='A'?1.5:1.2;c.setLineDash(side==='A'?[5,3]:[]);c.beginPath();let pen=false;
    if(S.source==='music'){const shift=side==='B'?S.align.shift:0,gain=side==='B'?S.align.gain:1,offset=side==='B'?S.align.offset:0,values=music[keys[j]],cols=Math.ceil(R-L);for(let x=0;x<cols;x++){const t0=win.start+x/cols*(win.end-win.start)-shift,t1=win.start+(x+1)/cols*(win.end-win.start)-shift,lo=Math.max(0,Math.ceil(t0*music.sampleRate)),hi=Math.min(values.length,Math.ceil(t1*music.sampleRate));if(hi<=lo)continue;let min=Infinity,max=-Infinity;for(let n=lo;n<hi;n++){const v=gain*values[n]+offset;min=Math.min(min,v);max=Math.max(max,v);}if(min < -range||max > range)clipped=true;c.moveTo(L+x,Y(min));c.lineTo(L+x,Y(max));}}
    else{const count=Math.ceil(R-L);for(let i=0;i<=count;i++){const t=win.start+i/count*(win.end-win.start),v=sample(side,t);if(!v.valid){pen=false;continue;}if(Math.abs(v.channels[keys[j]])>range)clipped=true;const x=X(t),y=Y(v.channels[keys[j]]);pen?c.lineTo(x,y):c.moveTo(x,y);pen=true;}}
    c.stroke();}c.setLineDash([]);c.restore();}
  c.fillStyle='#a8c2c5';for(let i=0;i<=4;i++){const t=win.start+(win.end-win.start)*i/4;c.textAlign=i===4?'right':'center';c.fillText(t.toFixed(2)+' s',X(t),h-2);}
  signalPlotCache={key,canvas:layer,clipped};signalPlotBuilds++;
 }
 // Copy the exact cached axes/traces, then draw only the current selection.
 const c=canvas.getContext('2d');c.setTransform(1,0,0,1,0,0);c.drawImage(signalPlotCache.canvas,0,0);c.setTransform(dpr,0,0,dpr,0,0);c.strokeStyle='#f2ede1';c.lineWidth=1.2;c.setLineDash([]);
 for(let j=0;j<2;j++){const top=22+j*(h-30)/2,bot=top+(h-30)/2-25;c.save();c.beginPath();c.rect(L,top,R-L,bot-top);c.clip();c.beginPath();c.moveTo(X(S.transport.time),top);c.lineTo(X(S.transport.time),bot);c.stroke();c.restore();}
 const clipped=signalPlotCache.clipped;canvas.dataset.plotCache=rebuild?'rebuilt':'reused';canvas.dataset.plotBuilds=String(signalPlotBuilds);canvas.dataset.clipped=String(clipped);$('signalHint').textContent=clipped?'Values exceed fixed axes · exact samples remain inspectable':S.source==='music'?'Native PCM min/max bins · click to scrub':'Click to scrub · Shift-drag to align B';canvas.dataset.window=JSON.stringify(win);canvas.dataset.selection=String(S.transport.time);canvas.setAttribute('aria-label',(S.source==='music'?'Native stereo PCM min/max waveform':'Generated position and velocity signals')+'. Shared time '+S.transport.time.toFixed(6)+' s. Window '+win.start+' to '+win.end+' s; fixed channel ranges '+ranges.join(', ')+'. Reference amber, candidate cyan.');
}
function sourceLinkHtml(state=S){
 let paths;
 if(state.source==='lake'){
  const files=[...(D.lakes.selectedSubset.sourceFiles||[]),...D.lakes.entryPoints.flatMap(entry=>entry.inspectedFiles||[])];
  paths=files.filter(file=>file?.bundled===true&&typeof file.path==='string'&&file.path.startsWith('data/lakes/')&&file.path.split('/').every(part=>part!=='.'&&part!=='..'&&/^[A-Za-z0-9_.-]+$/.test(part))).map(file=>file.path);
 }else paths=state.source==='music'?['data/music.wav','data/music.json']:['model.js'];
 return [...new Set(paths)].map(path=>'<a href="'+esc(path)+'" target="_blank" rel="noopener">Retained raw file: '+esc(path.split('/').at(-1))+'</a>').join('<br>');
}
function inspect(){const lake=S.source==='lake',t=S.transport.time,a=lake?null:sample('A',t),b=lake?null:sample('B',t);$('sourceLinks').innerHTML=sourceLinkHtml();$('inspectionSummary').innerHTML='<p>'+esc(lake?'Native catalogue; no observation-time signal.':'One cursor drives the form, signals and sample selection.')+'</p>';const selected=inspectionContribution(S);if(selected)$('inspectionSummary').innerHTML+='<p><strong>'+esc(selected.side+' · '+(selected.label||selected.key))+'</strong><br>'+esc(selected.value==null?'Outside native support':String(selected.value)+' '+selected.unit)+'<br><span class=small>Native time '+esc(String(selected.nativeTime))+' s</span></p>';$('nativeDetails').textContent=pretty(lake?selectedLake():{selectedContribution:selected,displayTime:t,reference:a,candidate:b,formFrames:{a:formSample('A',t),b:formSample('B',t)}});$('sourceDetails').textContent=pretty(lake?{record:selectedLake(),sourceFiles:D.lakes.selectedSubset.sourceFiles,timeSemantics:D.lakes.selectedSubset.timeSemantics}:S.source==='music'?D.music.metadata:{kind:'generated',reference:M.reference,candidate:S.tune,sourceFingerprint:D.sources.oscillator,alternatives:S.alternatives});$('receiptDetails').textContent=pretty({transform:M.recipeReceipt(S),rendering:renderingRecord(S),metrics:metric});$('lakeDetails').textContent=pretty({entries:D.lakes.entryPoints,coverage:D.lakes.selectedSubset.coverage,limitations:D.lakes.selectedSubset.limitations});}
function selectedLake(){return D.lakes.selectedSubset.records.find(r=>r.id===S.selectedLakeId)||D.lakes.selectedSubset.records.find(r=>r.id==='USA')||D.lakes.selectedSubset.records[0];}
function renderLake(){const subset=D.lakes.selectedSubset,r=selectedLake();S.selectedLakeId=r.id;$('lakeStage').innerHTML='<h2>Knowledge lakes / source entry</h2><p class="small">'+esc(subset.label)+' · '+subset.records.length+' retained entity records. Capture dates are provenance, not per-record observation times.</p><div class="relation">'+D.lakes.entryPoints.map(e=>'<button data-lake-entry="'+esc(e.id)+'">'+esc(e.label||e.id)+'</button>').join('')+'</div><div class="notice">This is a static catalogue. It supports inspecting recorded relationships and coverage. It supplies no sampled economic or biological waveform for this workspace.</div><div class="lake-tools"><input id="lakeSearch" type="text" aria-label="Search retained lake entities" placeholder="Search country, aggregate, or native ID"><button id="lakeInspect">Inspect selected record</button></div><div class="relation" id="lakeRelations"></div><div class="lake-table-wrap"><table><thead><tr><th>Native identity</th><th>Recorded region</th><th>Income class</th><th>Kind</th></tr></thead><tbody id="lakeRows"></tbody></table></div>';$('lakeSearch').oninput=drawLakeRows;$('lakeInspect').onclick=()=>setTask('inspect');$('lakeStage').querySelectorAll('[data-lake-entry]').forEach(b=>b.onclick=()=>{setTask('inspect');S.inspection.openDetails=[...new Set([...S.inspection.openDetails,'lakes'])];syncInspectionDetails();status('Source entry: '+b.textContent+' · inspected local files and limits shown.');});drawLakeRows();}
function drawLakeRows(){const q=$('lakeSearch').value.toLowerCase(),r=selectedLake();$('lakeRows').innerHTML=D.lakes.selectedSubset.records.filter(x=>(x.id+' '+x.name).toLowerCase().includes(q)).map(x=>'<tr class="'+(x.id===r.id?'selected':'')+'"><td><button data-lake-id="'+esc(x.id)+'">'+esc(x.name)+' · '+esc(x.id)+'</button></td><td>'+esc(x.region.value||'missing')+'</td><td>'+esc(x.incomeLevel.value||'missing')+'</td><td>'+esc(x.region.value==='Aggregates'?'Aggregate':'Entity')+'</td></tr>').join('');$('lakeRows').querySelectorAll('[data-lake-id]').forEach(b=>b.onclick=()=>{S.selectedLakeId=b.dataset.lakeId;drawLakeRows();if(S.task==='inspect')inspect();});$('lakeRelations').innerHTML='<span><strong>'+esc(r.name)+'</strong> · '+esc(r.id)+'</span> → '+['region','adminregion','incomeLevel','lendingType'].map(k=>'<span>'+esc(k)+': '+esc(r[k]?.value||'missing')+'<br><small>native ID '+esc(r[k]?.id||'empty')+'</small></span>').join('');}
function chooseSource(source){stopAudio();S.transport.playing=false;S.audio.enabled=false;S.source=source;S.transport.time=0;S.transport.start=0;S.transport.end=16;S.align=source==='music'?{shift:.125,gain:.85,offset:0}:{shift:0,gain:1,offset:0};S.task=source==='lake'?'choose':'compare';S.inspection.contribution=null;metric=null;metricKey='';syncControls();paint(true);status(source==='music'?'Original generated stereo score loaded. Beat, bar, phrase and form annotations are supplied, not inferred.':source==='lake'?'Entered the retained lake subset. Temporal playback is unavailable for these static records.':'Fixed reference and generated candidate loaded.');}
function stopAudio(){audioGeneration++;audioOrigin=null;if(audioNode){try{audioNode.stop();}catch{}audioNode.disconnect();audioNode=null;}}
async function startAudio(){stopAudio();if(!S.audio.enabled||!S.transport.playing||S.source==='lake')return;try{const token=audioGeneration;audioContext=audioContext||new AudioContext();await audioContext.resume();if(token!==audioGeneration||!S.audio.enabled||!S.transport.playing)return;const key=JSON.stringify([S.source,S.tune,S.align,S.audio.mix]);if(audioKey!==key){const n=music.left.length,rate=music.sampleRate;audioBuffer=audioContext.createBuffer(2,n,rate);const out=[audioBuffer.getChannelData(0),audioBuffer.getChannelData(1)];let pa=0,pb=0;for(let i=0;i<n;i++){const t=i/rate;let av,bv;if(S.source==='music'){const nativeTime=t-S.align.shift,valid=nativeTime>=0&&nativeTime<music.duration,j=Math.min(n-1,Math.round(nativeTime*rate));av=[music.left[i],music.right[i]];bv=valid?[music.left[j]*S.align.gain+S.align.offset,music.right[j]*S.align.gain+S.align.offset]:[0,0];}else{const nt=t-S.align.shift,valid=nt>=0&&nt<=16,ax=Math.sin(Math.PI*t),bx=valid?S.align.gain*S.tune.amplitude*Math.exp(-S.tune.damping*nt)*Math.sin(2*Math.PI*S.tune.frequency*nt+S.tune.phase)+S.align.offset:0;pa+=2*Math.PI*Math.max(40,Math.min(880,220+110*ax))/rate;pb+=2*Math.PI*Math.max(40,Math.min(880,220+110*bx))/rate;const va=.12*Math.sin(pa),vb=valid?.12*Math.sin(pb):0;av=[va,va];bv=[vb,vb];}for(let ch=0;ch<2;ch++){const v=S.audio.mix==='a'?av[ch]:S.audio.mix==='b'?bv[ch]:(av[ch]+bv[ch])*.5;out[ch][i]=Math.max(-1,Math.min(1,v));}}audioKey=key;}audioNode=audioContext.createBufferSource();audioNode.buffer=audioBuffer;audioNode.loop=S.transport.loop;audioNode.loopStart=S.transport.start;audioNode.loopEnd=S.transport.end;audioNode.playbackRate.value=S.transport.speed;const filter=audioContext.createBiquadFilter();filter.type='highpass';filter.frequency.value=20;const gain=audioContext.createGain();gain.gain.value=.35;audioNode.connect(filter);filter.connect(gain);gain.connect(audioContext.destination);audioOrigin={time:S.transport.time,contextTime:audioContext.currentTime,speed:S.transport.speed};audioNode.start(audioOrigin.contextTime,Math.min(S.transport.time,16-.001));lastTick=performance.now();status(S.source==='music'?'Listening to retained stereo PCM through the shared transport.':'Listening to declared oscillator sonification; audible pitch is a display mapping, not the native 0.5 Hz signal.');}catch(e){S.audio.enabled=false;status('Audio unavailable: '+e.message,true);syncControls();}}
function seek(time){S.inspection.contribution=null;S.transport.time=Math.max(S.transport.start,Math.min(S.transport.end,time));lastTick=performance.now();paint(true);if(S.audio.enabled)startAudio();}
function togglePlay(){if(S.transport.time>=S.transport.end)S.transport.time=S.transport.start;S.transport.playing=!S.transport.playing;S.inspection.contribution=null;lastTick=performance.now();syncControls();if(S.transport.playing)startAudio();else stopAudio();paint(true);}
function change(){S.inspection.contribution=null;M.validateState(S);metricKey='';syncControls();paint(true);if(S.audio.enabled&&S.transport.playing)startAudio();}
function modal(mode){$('modalTitle').textContent=mode==='save'?'Save complete interaction state':'Restore an interaction';$('modalNote').textContent=mode==='save'?'Source fingerprints, generated alternatives, Align, Tune, shared time, camera, form, listening and layout settings are included.':'Restore validates source fingerprints and recomputes transformation and rendering records. A playing, audible save resumes only through this explicit restore action.';$('applySession').hidden=mode==='save';$('downloadSession').hidden=mode!=='save';$('chooseSession').hidden=mode==='save';$('sessionText').value=mode==='save'?pretty(M.save(S,{sources:D.sources,renderingRecord})):'';$('modalError').textContent='';$('modalBackdrop').hidden=false;}
document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>setTask(b.dataset.task));document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>chooseSource(b.dataset.source));$('changeSource').onclick=()=>setTask('choose');$('alignTab').onclick=()=>setTask('align');$('tuneTab').onclick=()=>setTask('tune');$('inspectDifference').onclick=()=>setTask('inspect');$('encoding').onchange=e=>{S.encoding=e.target.value;paint(true);};$('homeCamera').onclick=()=>{scene.home();S.camera=scene.getCamera();paint(true);};
for(const k of ['shift','gain','offset'])$(k).oninput=e=>{S.align[k]=+e.target.value;change();};for(const k of ['frequency','amplitude','phase','damping'])$(k).oninput=e=>{S.tune[k]=+e.target.value;change();};$('resetAlign').onclick=()=>{S.align={shift:0,gain:1,offset:0};change();};$('resetTune').onclick=()=>{S.tune=clone(M.defaultState().tune);change();};$('keepCandidate').onclick=()=>{if(S.alternatives.length>=12){status('Twelve candidate recipes are already retained.',true);return;}S.alternatives.push({name:'Candidate '+(S.alternatives.length+1)+' · '+S.tune.frequency.toFixed(3)+' Hz',tune:clone(S.tune)});syncControls();status('Generated candidate recipe retained in this session.');};$('candidateSelect').onchange=e=>{if(e.target.value!=='current'){const a=S.alternatives[+e.target.value];S.tune=clone(a.tune);change();}};
 $('play').onclick=togglePlay;$('stepBack').onclick=()=>{S.transport.playing=false;stopAudio();seek(S.transport.time-S.transport.step);syncControls();};$('stepForward').onclick=()=>{S.transport.playing=false;stopAudio();seek(S.transport.time+S.transport.step);syncControls();};$('scrub').oninput=e=>seek(+e.target.value);$('loop').onchange=e=>{S.transport.loop=e.target.checked;if(S.audio.enabled)startAudio();};for(const k of ['speed','span','persistence'])$(k).onchange=e=>{S.transport[k]=+e.target.value;change();};$('listen').onclick=()=>{S.audio.enabled=!S.audio.enabled;if(S.audio.enabled){S.inspection.contribution=null;if(S.transport.time>=S.transport.end)S.transport.time=S.transport.start;S.transport.playing=true;lastTick=performance.now();startAudio();}else stopAudio();syncControls();};$('audioMix').onchange=e=>{S.audio.mix=e.target.value;startAudio();};
 $('signalCanvas').onpointerdown=e=>{const b=e.currentTarget.getBoundingClientRect();S.inspection.contribution=null;signalDrag={x:e.clientX,shift:S.align.shift,align:e.shiftKey,bounds:b};e.currentTarget.setPointerCapture(e.pointerId);if(!e.shiftKey){const w=windowFor();seek(w.start+Math.max(0,Math.min(1,(e.clientX-b.left-64)/(b.width-84)))*(w.end-w.start));}};$('signalCanvas').onpointermove=e=>{if(signalDrag?.align){const w=windowFor();S.align.shift=Math.max(-2,Math.min(2,signalDrag.shift+(e.clientX-signalDrag.x)/(signalDrag.bounds.width-84)*(w.end-w.start)));metricKey='';syncControls();paint(true);}};$('signalCanvas').onpointerup=e=>{if(signalDrag?.align&&S.audio.enabled)startAudio();signalDrag=null;};
 $('save').onclick=()=>{try{modal('save');}catch(e){status(e.message,true);}};$('restore').onclick=()=>modal('restore');$('closeModal').onclick=()=>$('modalBackdrop').hidden=true;$('applySession').onclick=()=>{try{const next=M.restore(JSON.parse($('sessionText').value),{sources:D.sources,renderingRecord}).state;if(next.source==='lake'&&!D.lakes.selectedSubset.records.some(r=>r.id===next.selectedLakeId))throw Error('Selected lake identity is unavailable in the retained source');if(next.transport.end>16)throw Error('Playback window exceeds retained audio');stopAudio();S=next;lastTick=performance.now();metric=null;metricKey='';syncControls();paint(true);$('modalBackdrop').hidden=true;if(S.audio.enabled&&S.transport.playing)startAudio();status('Restored complete validated interaction state.');}catch(e){$('modalError').textContent=e.message;}};$('downloadSession').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([$('sessionText').value],{type:'application/json'}));a.download='canon-observatory-session.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};$('chooseSession').onclick=()=>$('sessionFile').click();$('sessionFile').onchange=async e=>{if(e.target.files[0])$('sessionText').value=await e.target.files[0].text();};
 let resizing=false;$('signalPanel').onpointerdown=e=>{const b=e.currentTarget.getBoundingClientRect();resizing=e.clientX>b.right-25&&e.clientY>b.bottom-25;};document.addEventListener('pointerup',()=>{if(resizing){S.panel.height=Math.max(180,Math.min(1000,$('signalPanel').clientHeight-85-(S.source==='music'?35:0)));resizing=false;}});new ResizeObserver(()=>{if(S.source!=='lake'){const h=$('signalPanel').clientHeight-75-(S.source==='music'?35:0);$('signalCanvas').style.height=Math.max(150,h-35)+'px';paintSignal();}}).observe($('signalPanel'));
 function tick(now){const dt=Math.max(0,(now-lastTick)/1000);lastTick=now;if(S.transport.playing&&S.source!=='lake'){S.transport.time=audioNode&&audioOrigin?audioOrigin.time+(audioContext.currentTime-audioOrigin.contextTime)*audioOrigin.speed:S.transport.time+dt*S.transport.speed;if(S.transport.time>=S.transport.end){if(S.transport.loop)S.transport.time=S.transport.start+(S.transport.time-S.transport.start)%(S.transport.end-S.transport.start);else{S.transport.time=S.transport.end;S.transport.playing=false;stopAudio();syncControls();}}}if(now-lastDraw>40&&(S.transport.playing||lastDraw===0)){paint();lastDraw=now;}requestAnimationFrame(tick);}
 syncControls();paint(true);requestAnimationFrame(tick);status('Ready. A is fixed; play to see drift, Align the comparison, or Tune B’s model.');
})();
